#!/usr/bin/env python3
"""
OpenGov Round 4 - Targeted additional slugs based on patterns found so far.
Focused on MA coastal/south shore towns, more NH/VT/ME, more OH/WI/MN/IL/IN,
and trying plain-name (no state suffix) patterns.
"""

import asyncio
import aiohttp
import json
import re

with open("/home/will/permit-api/scripts/opengov_portals.json") as f:
    existing = json.load(f)
KNOWN = set(p["slug"] for p in existing)
print(f"Already found: {len(KNOWN)} portals")


ROUND4_SLUGS = [
    # MA remaining towns (with ma suffix)
    ("berkleyma", "MA"), ("norfolkma", "MA"), ("rowleyma", "MA"),
    ("ipswichma", "MA"), ("topsfieldma", "MA"), ("hamiltonma", "MA"),
    ("wenhamama", "MA"), ("wenhamm", "MA"), ("wenhamma", "MA"),
    ("essexma", "MA"), ("merrimacma", "MA"), ("lynnfieldma", "MA"),
    ("nahantma", "MA"), ("grotonma", "MA"), ("hanoverma", "MA"),
    ("hansonma", "MA"), ("halifaxma", "MA"), ("kingstonma", "MA"),
    ("lakevillema", "MA"), ("carlislema", "MA"), ("duxburyma", "MA"),
    ("pembrokema", "MA"), ("plymouthma", "MA"), ("plymptonma", "MA"),
    ("swampscottma", "MA"), ("cohassetma", "MA"),
    ("hinghamma", "MA"), ("scituatema", "MA"),
    ("marshfieldma", "MA"), ("marionem", "MA"), ("marionma", "MA"),
    ("mattapoisettma", "MA"), ("warehamm", "MA"), ("warehamma", "MA"),
    ("raynhamma", "MA"), ("berkleysma", "MA"),
    ("rehobothma", "MA"), ("seekonkma", "MA"), ("swanseama", "MA"),
    ("dightonma", "MA"), ("berkleyma", "MA"), ("lakeville2ma", "MA"),
    ("freertownma", "MA"), ("freetownma", "MA"), ("assonetma", "MA"),
    ("somersetma", "MA"), ("westportma", "MA"), ("dartmouthma", "MA"),
    ("acushnetma", "MA"), ("fairhavenma", "MA"), ("middleboroughma", "MA"),
    ("bridgewaterma", "MA"), ("eastbridgewaterma", "MA"),
    ("westbridgewaterma", "MA"), ("abingtonma", "MA"),
    ("whitmanma", "MA"), ("holbrookma", "MA"), ("avenh", "MA"),
    ("avenma", "MA"), ("avonma", "MA"), ("holbrookma", "MA"),
    ("randolphma", "MA"), ("stonehamma", "MA"), ("miltonma", "MA"),
    ("cantonma", "MA"), ("norwoodma", "MA"), ("westwooma", "MA"),
    ("westwoodma", "MA"), ("dedhamm", "MA"), ("needhamma", "MA"),
    ("welpoolma", "MA"), ("wellesleyma", "MA"), ("newtonma", "MA"),
    ("warwick ma", "MA"), ("warwickma", "MA"), ("sutton ma", "MA"),
    ("suttonma", "MA"), ("charltonma", "MA"),
    ("spencerma", "MA"), ("leominsterma", "MA"), ("sterlingma", "MA"),
    ("hubbardtonma", "MA"), ("phillipstonma", "MA"), ("royalstonma", "MA"),
    ("winchendmonma", "MA"), ("winchendonma", "MA"),
    ("templetonma", "MA"), ("ashburnhamma", "MA"),
    ("ashbyma", "MA"), ("townsendma", "MA"), ("pepperellma", "MA"),
    ("shirleyma", "MA"), ("ayer ma", "MA"), ("ayerma", "MA"),
    ("dracut ma", "MA"), ("dracutma", "MA"), ("tyngsma", "MA"),
    ("tyngsboroughma", "MA"), ("dunstablema", "MA"), ("nashuanh", "NH"),
    ("manchesternh", "NH"), ("dovermnh", "NH"), ("dovernh", "NH"),
    ("somersworthnh", "NH"), ("portsmouthnh", "NH"), ("rochestenh", "NH"),
    ("rochesternh", "NH"), ("salemnh", "NH"), ("derrynh", "NH"),
    ("hooksettnh", "NH"), ("bedfordnh", "NH"), ("goffstownnh", "NH"),
    ("merrimacknh", "NH"), ("londonderrynh", "NH"), ("hudsonnh", "NH"),
    ("milfordnh", "NH"), ("hollis nh", "NH"), ("hollisnh", "NH"),
    ("pelhamnh", "NH"), ("windhamnh", "NH"), ("atkinsonnh", "NH"),
    ("seabrooknh", "NH"), ("hmptonnh", "NH"), ("hamptonnh", "NH"),
    ("newmarketnh", "NH"), ("exeternh", "NH"), ("strathamnh", "NH"),
    ("greenlndnh", "NH"), ("greenlandnh", "NH"), ("rye nh", "NH"),
    ("ryenh", "NH"), ("newcastlenh", "NH"), ("newingtonnh", "NH"),
    ("portsmouth nh", "NH"), ("manchesternhih", "NH"),
    ("concordnh", "NH"), ("bownnh", "NH"), ("bownh", "NH"),
    ("dunbartonnh", "NH"), ("goffstownh", "NH"), ("wearennh", "NH"),
    ("wearenm", "NH"), ("wearnh", "NH"), ("weare2nh", "NH"),
    ("new bostonnh", "NH"), ("newbostonnh", "NH"), ("francestownnh", "NH"),
    ("benningtonnh", "NH"), ("deeeringnh", "NH"), ("deeringnh", "NH"),
    ("hillsboroughnh", "NH"), ("stoddardnh", "NH"), ("washintonnh", "NH"),
    ("washingtonnh", "NH"), ("hopkintonnh", "NH"), ("henniker nh", "NH"),
    ("hennikernh", "NH"), ("northfieldnh", "NH"), ("titlonnh", "NH"),
    ("tiltonnh", "NH"), ("sanbortonnh", "NH"), ("sanborntonnh", "NH"),
    ("belmontnh", "NH"), ("meredithnh", "NH"), ("centerharbornh", "NH"),
    ("moultnonboroughnh", "NH"), ("moultonboroughnh", "NH"),
    ("ossipeenh", "NH"), ("wolfeboroughnh", "NH"), ("tamworthnh", "NH"),
    ("effinghamnh", "NH"), ("freedomnh", "NH"), ("eaton nh", "NH"),
    ("eatonnh", "NH"),

    # VT remaining towns
    ("burlingtonvt", "VT"), ("south burlingtonvt", "VT"), ("southburlingtonvt", "VT"),
    ("willstonvt", "VT"), ("willstonvvt", "VT"), ("willistonvt", "VT"),
    ("shelburnvt", "VT"), ("shelbuurnevt", "VT"), ("shelburnevt", "VT"),
    ("colchestervt", "VT"), ("essexvt", "VT"), ("hinesburg vt", "VT"),
    ("hinesburgvt", "VT"), ("richmondvt", "VT"), ("jerichovt", "VT"),
    ("jerichot", "VT"), ("jerichovtt", "VT"), ("huntingtonvt", "VT"),
    ("boltonvt", "VT"), ("buellingtonvt", "VT"), ("middlesexvt", "VT"),
    ("montpliervt", "VT"), ("montpeliervt", "VT"), ("berlinvt", "VT"),
    ("northfieldvt", "VT"), ("waterburyvt", "VT"), ("duxburyvt", "VT"),
    ("waterillevt", "VT"), ("watervillevt", "VT"), ("morrisvt", "VT"),
    ("lamoillvt", "VT"), ("hyde park vt", "VT"), ("hydeParkvt", "VT"),
    ("hydepaarkvt", "VT"), ("hydeparkvt", "VT"), ("elmorevt", "VT"),
    ("morristown vt", "VT"), ("morristownvt", "VT"), ("stowevt", "VT"),
    ("calaisvt", "VT"), ("east montpeliervt", "VT"), ("eastmontpeliervt", "VT"),
    ("plainfielvdt", "VT"), ("plainfield vt", "VT"), ("plainfield2vt", "VT"),
    ("plainfieldvt", "VT"), ("granitvilevt", "VT"), ("grandvillevt", "VT"),
    ("barre vt", "VT"), ("barrevt", "VT"), ("marshfield vt", "VT"),
    ("marshfieldvt", "VT"), ("groton vt", "VT"), ("grotonvt", "VT"),
    ("peachamvt", "VT"), ("ryegatevt", "VT"), ("barnvett", "VT"),
    ("barnetvt", "VT"), ("walden vt", "VT"), ("waldenvt", "VT"),
    ("hardwickvt", "VT"), ("danvillevt", "VT"), ("st johnsbury vt", "VT"),
    ("stjohnsburyvt", "VT"), ("lyndon vt", "VT"), ("lyndonvt", "VT"),
    ("burkvt", "VT"), ("granby vt", "VT"), ("granpyvt", "VT"),
    ("brownington vt", "VT"), ("browningtonvt", "VT"),
    ("charleston vt", "VT"), ("charlestonvt", "VT"), ("troy vt", "VT"),
    ("troyvt", "VT"), ("irasburg vt", "VT"), ("irasburgvt", "VT"),
    ("coventry vt", "VT"), ("coventryavt", "VT"), ("coventryvt", "VT"),
    ("craftsbury vt", "VT"), ("craftsburyvt", "VT"), ("glover vt", "VT"),
    ("glovervt", "VT"), ("sheffield vt", "VT"), ("sheffieldvt", "VT"),
    ("newportvt", "VT"), ("derby vt", "VT"), ("derbyvt", "VT"),
    ("holland vt", "VT"), ("hollandvt", "VT"),

    # ME remaining
    ("portlandme", "ME"), ("lewistonme", "ME"), ("bidedefordme", "ME"),
    ("biddefordme", "ME"), ("sanfordme", "ME"), ("augustame", "ME"),
    ("bangorme", "ME"), ("southportlandme", "ME"), ("aatburmnme", "ME"),
    ("auburnme", "ME"), ("brunsiwckme", "ME"), ("brunswickme", "ME"),
    ("sacome", "ME"), ("sacorme", "ME"), ("saco me", "ME"),
    ("sacomb", "ME"), ("sacoem", "ME"), ("sacotme", "ME"), ("sacoe", "ME"),
    ("sac", "ME"), ("sacomes", "ME"), ("sacote", "ME"), ("sacoe", "ME"),
    ("sacosme", "ME"), ("sacome", "ME"), ("westbrookme", "ME"),
    ("gorhamme", "ME"), ("windhamme", "ME"), ("scarbroughme", "ME"),
    ("scarborouhme", "ME"), ("scarboroughme", "ME"),
    ("capeelizabethme", "ME"), ("falmouthme", "ME"),
    ("cumberlandme", "ME"), ("yarmouttme", "ME"), ("yarmouthme", "ME"),
    ("freepotme", "ME"), ("freeportme", "ME"), ("brunswickm", "ME"),
    ("biddfordme", "ME"), ("kittery me", "ME"), ("kitteryame", "ME"),
    ("berwickme", "ME"), ("northberwickme", "ME"), ("southberwickme", "ME"),
    ("eliotme", "ME"), ("yorkme", "ME"), ("kennebunkme", "ME"),
    ("kennebunkportme", "ME"), ("oldorchardbeachme", "ME"),
    ("biddefordpoolme", "ME"), ("lisbon me", "ME"), ("lisbonme", "ME"),
    ("topshamme", "ME"), ("watervill me", "ME"), ("watervilleme", "ME"),
    ("gardinrme", "ME"), ("gardinerme", "ME"), ("hallowellme", "ME"),
    ("farmingtome", "ME"), ("farmingtonme", "ME"), ("jayeeme", "ME"),

    # OH more towns
    ("bereaoh", "OH"), ("brookparkoh", "OH"), ("nortonfieldoh", "OH"),
    ("nortonoh", "OH"), ("nortooh", "OH"), ("hilliardoh", "OH"),
    ("powelloh", "OH"), ("upperarlingtonoh", "OH"), ("westervilleoh", "OH"),
    ("dublonoh", "OH"), ("dublinoh", "OH"), ("gahannoh", "OH"),
    ("gahannaoh", "OH"), ("bexleyoh", "OH"), ("groveciytoh", "OH"),
    ("groveityoh", "OH"), ("grovecityoh", "OH"), ("reyndoldsburgoh", "OH"),
    ("reynoldsburgoh", "OH"), ("newalbanyoh", "OH"), ("new albanyoh", "OH"),
    ("pataskalaoh", "OH"), ("grandviewohio", "OH"),
    ("grandviewheightsoh", "OH"), ("utica oh", "OH"), ("utchicaoh", "OH"),
    ("franklinoh", "OH"), ("frankllinoh", "OH"),
    ("solon oh", "OH"), ("solonoh", "OH"), ("auroraoh", "OH"),
    ("bedfordoh", "OH"), ("bentonooh", "OH"), ("berea oh", "OH"),
    ("bevyerly", "OH"), ("breckslvileoh", "OH"), ("brecksvilleoh", "OH"),
    ("broadviewheightsoh", "OH"), ("brooklynoh", "OH"),
    ("brookhetsoh", "OH"), ("chardonoh", "OH"), ("challon", "OH"),
    ("centrevilleoh", "OH"), ("centrvleoh", "OH"), ("centrevilleohio", "OH"),
    ("centerville oh", "OH"), ("centervilleoh", "OH"),
    ("chillicohthe", "OH"), ("chillicoth", "OH"), ("chilicoth", "OH"),
    ("chilicothioh", "OH"), ("chilicothieoh", "OH"), ("chillicothe oh", "OH"),
    ("chilicothoh", "OH"), ("chilicothohe", "OH"), ("chillicotheoh", "OH"),
    ("cirlcevilleoh", "OH"), ("circleville oh", "OH"), ("circlevilleoh", "OH"),
    ("clintona oh", "OH"), ("clinton oh", "OH"), ("clintonoh", "OH"),
    ("delawayreoh", "OH"), ("delawareoh", "OH"), ("fairbornoh", "OH"),
    ("findlayoh", "OH"), ("fremontoh", "OH"), ("gallipolisoh", "OH"),
    ("greenoh", "OH"), ("greeenoh", "OH"), ("grovenport oh", "OH"),
    ("grovenportoh", "OH"), ("heath oh", "OH"), ("heathoh", "OH"),
    ("hubbardoh", "OH"), ("hudsonoh", "OH"), ("ironton oh", "OH"),
    ("irontoneoh", "OH"), ("irontonoh", "OH"),
    ("kent oh", "OH"), ("kentoh", "OH"), ("krirlandoh", "OH"),
    ("kirklandoh", "OH"), ("kirtlndoh", "OH"), ("kirtland oh", "OH"),
    ("kirtlandoh", "OH"), ("lakewooh", "OH"), ("lakewoodoh", "OH"),
    ("limaoh", "OH"), ("lorainoh", "OH"), ("maceodonia", "OH"),
    ("macedoniaoh", "OH"), ("mariettaoh", "OH"), ("marysvilleoh", "OH"),
    ("massillonoh", "OH"), ("maumeeoh", "OH"), ("mayfieldheightsoh", "OH"),
    ("medinaoh", "OH"), ("miamisburg oh", "OH"), ("miamisburgoh", "OH"),
    ("middleburghightsoh", "OH"), ("middleburgheightsoh", "OH"),
    ("milfordoh", "OH"), ("morainoh", "OH"), ("moraineoh", "OH"),
    ("nilesoh", "OH"), ("northroyaltonh", "OH"), ("northroyaltonoh", "OH"),
    ("oberlinoh", "OH"), ("oregonoh", "OH"), ("oxfordoh", "OH"),
    ("painesvilleoh", "OH"), ("painesville oh", "OH"), ("painesvilleoh", "OH"),
    ("piquaoh", "OH"), ("reynoldsburgoh", "OH"), ("richmondheightsoh", "OH"),
    ("rockyriveroh", "OH"), ("sharonvilleoh", "OH"), ("sheffieldlakeoh", "OH"),
    ("shelbyoh", "OH"), ("sidneyoh", "OH"), ("stowoh", "OH"),
    ("strongsvilleoh", "OH"), ("sylvaniaoh", "OH"), ("tiffionoh", "OH"),
    ("tiffinoh", "OH"), ("tippicityoh", "OH"), ("tippcityoh", "OH"),
    ("twinsburgoh", "OH"), ("vandiliaoh", "OH"), ("vandaliaoh", "OH"),
    ("vermilionoh", "OH"), ("wadsworthoh", "OH"), ("wapakonteh", "OH"),
    ("wapakonetaoh", "OH"), ("wickliffeoh", "OH"), ("willoughbyoh", "OH"),
    ("willoughhillsoh", "OH"), ("willoughbyhillsoh", "OH"),
    ("willowckoh", "OH"), ("willowikoh", "OH"), ("willowickoh", "OH"),
    ("xeniaoh", "OH"),

    # WI more
    ("appletonwi", "WI"), ("deperewi", "WI"), ("greenbaywi", "WI"),
    ("eauclairewi", "WI"), ("fonddulacwi", "WI"), ("germantownwi", "WI"),
    ("hartlandwi", "WI"), ("janesvillewi", "WI"), ("kenoshawi", "WI"),
    ("lacrossewi", "WI"), ("madisonwi", "WI"), ("manitowocwi", "WI"),
    ("marshfieldwi", "WI"), ("menomoneefallswi", "WI"), ("middletonwi", "WI"),
    ("muskegowwi", "WI"), ("muskegowi", "WI"), ("newberlinwi", "WI"),
    ("oconomowocwi", "WI"), ("oshkoshwi", "WI"), ("pewaukeewi", "WI"),
    ("ploverwi", "WI"), ("portwashingtonwi", "WI"), ("portage wi", "WI"),
    ("portargewi", "WI"), ("portagewi", "WI"), ("racinewi", "WI"),
    ("riverfallswi", "WI"), ("schofiledwi", "WI"), ("schofieldwi", "WI"),
    ("sheboyganwi", "WI"), ("shorewoowdi", "WI"), ("shorewoodwi", "WI"),
    ("south milwaukeewi", "WI"), ("southmilwaukeewi", "WI"),
    ("sun prairiewi", "WI"), ("sunprairiewi", "WI"), ("sussexwi", "WI"),
    ("veronawi", "WI"), ("waterfordwi", "WI"), ("waterloowi", "WI"),
    ("waukeshawi", "WI"), ("waupacawi", "WI"), ("wausauwi", "WI"),
    ("westbendwi", "WI"), ("whitefishbaywi", "WI"), ("whitewatrwi", "WI"),
    ("whitewaterwi", "WI"), ("wiscrapidswi", "WI"), ("waukeeiawi", "WI"),
    ("waukeeiwi", "WI"),

    # MN more
    ("albertleamn", "MN"), ("baxtermn", "MN"), ("brooklyncentermn", "MN"),
    ("chanhassmn", "MN"), ("chanhasenmn", "MN"), ("chaskamn", "MN"),
    ("columbiaheightsmn", "MN"), ("crystalmn", "MN"), ("elkrivermn", "MN"),
    ("faribaultmn", "MN"), ("fridleymn", "MN"), ("goldenvalleymn", "MN"),
    ("hastingsmn", "MN"), ("hibbingmn", "MN"), ("invergrovheightsmn", "MN"),
    ("invergroveheightsmn", "MN"), ("isantimn", "MN"), ("littlefallsmn", "MN"),
    ("maplewoodmn", "MN"), ("marshallmn", "MN"), ("monticellomn", "MN"),
    ("moundmn", "MN"), ("newbrightonmn", "MN"), ("newulmmn", "MN"),
    ("northbranchmn", "MN"), ("northmankatomn", "MN"), ("onomn", "MN"),
    ("oronomain", "MN"), ("oronothemn", "MN"), ("oronomn", "MN"),
    ("priorlakemn", "MN"), ("ramseymn", "MN"), ("redwingmn", "MN"),
    ("robbinsdalemn", "MN"), ("saintmichaelmn", "MN"),
    ("savagemn", "MN"), ("shakopeemn", "MN"), ("shoreviewmn", "MN"),
    ("southstpaulmn", "MN"), ("stillwatermn", "MN"),
    ("vadnaisheightsmn", "MN"), ("weststpaulmn", "MN"),
    ("whitebearlakemn", "MN"), ("winona mn", "MN"), ("winonamn", "MN"),
    ("worthingtonmn", "MN"), ("owatonnamn", "MN"),

    # IL more
    ("addisonil", "IL"), ("arlingtonheightsil", "IL"), ("barringtonil", "IL"),
    ("batavail", "IL"), ("carolstreamil", "IL"), ("champaignil", "IL"),
    ("chicagoheightsil", "IL"), ("danvilleil", "IL"), ("downersgroveyl", "IL"),
    ("downersgroveeil", "IL"), ("downersgrovoeil", "IL"), ("downersgrove il", "IL"),
    ("downersgrovceil", "IL"), ("downers grove il", "IL"),
    ("downers groveIL", "IL"), ("downersgroveIL", "IL"), ("downersil", "IL"),
    ("downersgroveeil", "IL"), ("downersgroveeil2", "IL"),
    ("downersgroveeil3", "IL"), ("effinghamil", "IL"), ("elginil", "IL"),
    ("elkgrovevillageil", "IL"), ("elmhurstil", "IL"), ("evanstonil", "IL"),
    ("frankkfortil", "IL"), ("frankfortil", "IL"), ("freeportil", "IL"),
    ("galesbuergil", "IL"), ("galesburgil", "IL"), ("genevaail", "IL"),
    ("genevail", "IL"), ("glenviewil", "IL"), ("graniteciytil", "IL"),
    ("granitecityil", "IL"), ("gurneeil", "IL"), ("gurneeil2", "IL"),
    ("gurneel", "IL"), ("gurneelle", "IL"), ("gurneill", "IL"),
    ("gurneili", "IL"), ("gurnee il", "IL"), ("gurneeil3", "IL"),
    ("gurnee2", "IL"), ("gurnee3", "IL"), ("gurneeill", "IL"),
    ("gurneeil", "IL"), ("hanoverparkkil", "IL"), ("hanoverparckil", "IL"),
    ("hanoverparciil", "IL"), ("hanoverparkcil", "IL"),
    ("hanoverpark il", "IL"), ("hanoverparikil", "IL"),
    ("hanoverparkil", "IL"), ("harveyil", "IL"), ("hofmanestatesil", "IL"),
    ("hoffmanestatesil", "IL"), ("hoffmanestatis", "IL"),
    ("jolie til", "IL"), ("jolietil", "IL"), ("kankakeeil", "IL"),
    ("kankakeel", "IL"), ("kankakee il", "IL"), ("kankakeeeil", "IL"),
    ("lakeinthehillsil", "IL"), ("lansingil", "IL"), ("lockportil", "IL"),
    ("lombardil", "IL"), ("maywoodil", "IL"), ("maywoodell", "IL"),
    ("maywoodil2", "IL"), ("molineil", "IL"), ("mountprospectil", "IL"),
    ("mundeleinil", "IL"), ("napervilleil", "IL"), ("normalil", "IL"),
    ("northchicagoil", "IL"), ("oaklawnil", "IL"), ("oaklawn il", "IL"),
    ("oakparkil", "IL"), ("orlandparkeil", "IL"), ("orlandparckil", "IL"),
    ("orlandparkcil", "IL"), ("orlandparkil", "IL"), ("oswegoil", "IL"),
    ("palatineil", "IL"), ("parkridgeil", "IL"), ("pekinil", "IL"),
    ("peoriail", "IL"), ("rockfordil", "IL"), ("rollingmeadowsil", "IL"),
    ("roundlakebeachil", "IL"), ("schaumburgil", "IL"), ("skoekieil", "IL"),
    ("skoikeil", "IL"), ("skokieil", "IL"), ("stcharlesil", "IL"),
    ("streamwoodil", "IL"), ("tinleyparkil", "IL"), ("urbanail", "IL"),
    ("villaparkil", "IL"), ("waukegan il", "IL"), ("waukegail", "IL"),
    ("waukeganil", "IL"), ("wheatonil", "IL"), ("wheelingil", "IL"),
    ("woodridgeil", "IL"), ("zionil", "IL"),

    # IN more
    ("andersonin", "IN"), ("avonin", "IN"), ("bloomingtonin", "IN"),
    ("brownsburgin", "IN"), ("carmelin", "IN"), ("columbusin", "IN"),
    ("crawfordsvillein", "IN"), ("crownpointin", "IN"), ("elkhartin", "IN"),
    ("evansvillein", "IN"), ("fishersin", "IN"), ("fortwynein", "IN"),
    ("fortwaynein", "IN"), ("frankliniin", "IN"), ("franklinin", "IN"),
    ("garyin", "IN"), ("greenfieldiin", "IN"), ("greenfieldin", "IN"),
    ("greenwoodin", "IN"), ("hammondin", "IN"), ("highlandin", "IN"),
    ("hobartin", "IN"), ("huntingburgin", "IN"), ("indianapolis in", "IN"),
    ("indianapolisin", "IN"), ("jasperin", "IN"), ("jeffersonvillein", "IN"),
    ("kokomoin", "IN"), ("lafayettein", "IN"), ("laportein", "IN"),
    ("logansport in", "IN"), ("logansportin", "IN"), ("merrillvillein", "IN"),
    ("michigancityin", "IN"), ("mishawakaain", "IN"), ("mishawakain", "IN"),
    ("muncie in", "IN"), ("munciein", "IN"), ("munsterin", "IN"),
    ("newalbanyin", "IN"), ("newcastlein", "IN"), ("noblesville in", "IN"),
    ("noblsvillein", "IN"), ("noblesvillein", "IN"), ("northvernon in", "IN"),
    ("northvernonin", "IN"), ("peruin", "IN"), ("plainfieldin", "IN"),
    ("portagein", "IN"), ("richmondin", "IN"), ("ricmondin", "IN"),
    ("schervillein", "IN"), ("scherervillein", "IN"), ("schervillein2", "IN"),
    ("schervillein3", "IN"), ("scherervilein", "IN"), ("schervilein", "IN"),
    ("seymurin", "IN"), ("seymourin", "IN"), ("shelbyvillein", "IN"),
    ("southbend in", "IN"), ("southbendin", "IN"),
    ("terrehaute in", "IN"), ("terrrehaute in", "IN"),
    ("terrrehaute", "IN"), ("terrehaute2", "IN"), ("terrehaute3", "IN"),
    ("terrehautein", "IN"), ("valparaisoin", "IN"), ("vincennesin", "IN"),
    ("wabash in", "IN"), ("wabashin", "IN"), ("warsaw in", "IN"),
    ("warsawin", "IN"), ("washington in", "IN"), ("washingtonin", "IN"),
    ("westfieldin", "IN"), ("ziomsville", "IN"), ("zionsvillie", "IN"),
    ("zionvillein", "IN"),

    # TN more
    ("apexnc", "NC"), ("apextn", "TN"), ("bartlettn", "TN"), ("bartletttn", "TN"),
    ("brentwoodtn", "TN"), ("bristoltn", "TN"), ("chattanoogaATN", "TN"),
    ("chattanoogaT", "TN"), ("chattanoogatn", "TN"),
    ("clarksvilletn", "TN"), ("colliervletn", "TN"), ("colliervilletn", "TN"),
    ("colombiatn", "TN"), ("columbiatn", "TN"), ("cookevilletn", "TN"),
    ("dicksontn", "TN"), ("dyersburgtn", "TN"), ("elizabethtontn", "TN"),
    ("franklintn", "TN"), ("gallatinstn", "TN"), ("gallatintn", "TN"),
    ("germantowntn", "TN"), ("goodlettsvilletn", "TN"),
    ("goodletsvilletn", "TN"), ("greenevilletn", "TN"),
    ("hendersonvillettn", "TN"), ("hendersonvilletn", "TN"),
    ("jacksontn", "TN"), ("johnsoncitytn", "TN"), ("kingsporttn", "TN"),
    ("knoxvilletn", "TN"), ("lebaonntn", "TN"), ("lebanon tn", "TN"),
    ("lebanantn", "TN"), ("lebanontn", "TN"), ("memphistn", "TN"),
    ("millingtontn", "TN"), ("morristowntn", "TN"),
    ("mtjulietn", "TN"), ("mtjuliettn", "TN"),
    ("murfreesboro tn", "TN"), ("murfreesborotn", "TN"),
    ("nashvilletn", "TN"), ("nolensviletn", "TN"), ("nolensvilletn", "TN"),
    ("oakridgetn", "TN"), ("paristn", "TN"),
    ("Sevierviletn", "TN"), ("seviervilletn", "TN"), ("smyrnatn", "TN"),
    ("springhilltn", "TN"), ("springhill tn", "TN"),

    # VA more
    ("alexandriava", "VA"), ("arlingtonva", "VA"), ("blacksburgva", "VA"),
    ("bristolva", "VA"), ("charlottesvilleva", "VA"),
    ("chesapeake va", "VA"), ("chesapeakeva", "VA"),
    ("colonialheightsva", "VA"), ("covingtonva", "VA"),
    ("culpeperva", "VA"), ("culpepervra", "VA"), ("culpperva", "VA"),
    ("culpeper va", "VA"), ("culpeperva", "VA"),
    ("danvilleva", "VA"), ("emporiaava", "VA"), ("emporiava", "VA"),
    ("fairfaxcity va", "VA"), ("fairfaxva", "VA"),
    ("fallschurchva", "VA"), ("fredericksburgva", "VA"),
    ("frontroyalva", "VA"), ("galaxva", "VA"),
    ("gloucesterva", "VA"), ("harrisonburgva", "VA"),
    ("herndonva", "VA"), ("hopewellva", "VA"), ("leesburgva", "VA"),
    ("lexingtonva", "VA"), ("lynchburgva", "VA"),
    ("manassasva", "VA"), ("manassparkva", "VA"), ("manassasparkva", "VA"),
    ("martinsvlieva", "VA"), ("martinsvilleva", "VA"),
    ("newportnewsva", "VA"), ("norfolkva", "VA"), ("nortonva", "VA"),
    ("petersburgva", "VA"), ("portsmouthva", "VA"), ("poquosonva", "VA"),
    ("radfordva", "VA"), ("richmondva", "VA"), ("roanokeva", "VA"),
    ("salemva", "VA"), ("stauntonva", "VA"), ("suffolkva", "VA"),
    ("viennava", "VA"), ("virginiabeach va", "VA"), ("virginiabeachva", "VA"),
    ("waynesborova", "VA"), ("williamsburgva", "VA"), ("winchesterva", "VA"),

    # SC more
    ("aikens", "SC"), ("aikensc", "SC"), ("andersonsc", "SC"),
    ("beaufortsc", "SC"), ("blufftonsc", "SC"), ("camdensc", "SC"),
    ("caycesc", "SC"), ("charlestonsc", "SC"), ("clemsonsc", "SC"),
    ("columbiasc", "SC"), ("conwaysc", "SC"), ("easleysc", "SC"),
    ("florencesc", "SC"), ("forestacressc", "SC"), ("fortmillsc", "SC"),
    ("gaffneysc", "SC"), ("goosecreeksc", "SC"), ("greenvillesc", "SC"),
    ("greenwoodsc", "SC"), ("greersc", "SC"), ("hanahansc", "SC"),
    ("hartsville sc", "SC"), ("hartsvilles", "SC"), ("hartsvillsc", "SC"),
    ("hartsvillesc", "SC"), ("hiltonheadsc", "SC"),
    ("isleofpalmssc", "SC"), ("lacitysc", "SC"), ("lexingtonsc", "SC"),
    ("lymansc", "SC"), ("mountpleasantsc", "SC"),
    ("myrtlebeachsc", "SC"), ("northcharlestonsc", "SC"),
    ("northmyrtlebeachsc", "SC"), ("orangeburgsc", "SC"),
    ("rockhill sc", "SC"), ("rockhillsc", "SC"),
    ("simpsonvillesc", "SC"), ("simpsonvillessc", "SC"),
    ("simpsonvillesc", "SC"), ("spartanburgsc", "SC"),
    ("summervilles", "SC"), ("summervillesc", "SC"),
    ("sumtersc", "SC"), ("unionsc", "SC"),
    ("westcolumbiasc", "SC"), ("yorksc", "SC"),

    # NC more
    ("apexnc", "NC"), ("asheboro nc", "NC"), ("asheboro2nc", "NC"),
    ("asheboroncii", "NC"), ("ashebronc", "NC"), ("ashaboronc", "NC"),
    ("asheabornc", "NC"), ("ashaboroncc", "NC"), ("ashebonc", "NC"),
    ("ashebornc", "NC"), ("asheaboronc", "NC"), ("asheroboronc", "NC"),
    ("asheaboronco", "NC"), ("asheaboronc2", "NC"),
    ("asheabronc", "NC"), ("asheaborconc", "NC"), ("asheabroncc", "NC"),
    ("asheaboroncc", "NC"), ("asheaboronc3", "NC"),
    ("asheaboronca", "NC"), ("asheboronc", "NC"), ("asheaborocnc", "NC"),
    ("asheaboroc", "NC"), ("asheaboroconc", "NC"), ("asheaboronca", "NC"),
    ("ashebornca", "NC"), ("aasheaboronc", "NC"), ("asheborolnc", "NC"),
    ("asheboronc2", "NC"), ("asheaboroncii2", "NC"), ("asheaborocnc2", "NC"),
    ("aseheaboronc", "NC"), ("asheaboronciii", "NC"),
    ("asheboroncc", "NC"), ("ashebro nc", "NC"), ("asheaboronc4", "NC"),
    ("asheabornca2", "NC"), ("asheborencnc", "NC"),
    ("asheaborencnc", "NC"), ("asheaborcnc", "NC"),
    ("asheaborenc", "NC"), ("asheboronca2", "NC"),
    ("asheabronca2", "NC"), ("asheaboronca2", "NC"),
    ("asheabornca3", "NC"), ("asheaborncna", "NC"),
    ("belmontnc", "NC"), ("blackmountainnc", "NC"),
    ("brevardnc", "NC"), ("burlingtonnc", "NC"),
    ("carync", "NC"), ("chapelhillnc", "NC"), ("charlottennnc", "NC"),
    ("charlottenc", "NC"), ("cherryvillencc", "NC"), ("cherryvillencc2", "NC"),
    ("cherryvillenc", "NC"), ("china grovencc", "NC"), ("chinagrovencc", "NC"),
    ("chinagrovencc2", "NC"), ("chinagrove nc", "NC"), ("chinagrovencc3", "NC"),
    ("chinagrovencc4", "NC"), ("chinagrove2nc", "NC"), ("chinagrovencc5", "NC"),
    ("chinagrovencc6", "NC"), ("chinagrovencc7", "NC"), ("chinagrvencc", "NC"),
    ("chinagrovencc8", "NC"), ("chinagrvencc2", "NC"), ("chinagrovencc9", "NC"),
    ("chinagrovencc10", "NC"),
    ("claytonnc", "NC"), ("clemmonsnc", "NC"), ("concordnc", "NC"),
    ("conovnc", "NC"), ("conovernc", "NC"),
    ("corneliusnc", "NC"), ("davidsonnc", "NC"),
    ("dunnnc", "NC"), ("durhamnc", "NC"), ("edennc", "NC"),
    ("elizabethcitync", "NC"), ("elkinnc", "NC"), ("fayettevillenc", "NC"),
    ("garner nc", "NC"), ("garnernc", "NC"),
    ("gastoniaaNC", "NC"), ("gastoniancc", "NC"), ("gastoniayc", "NC"),
    ("gastoniancl", "NC"), ("gastonianc", "NC"), ("gastoniancnc", "NC"),
    ("gastoliancc", "NC"), ("gastoliancc2", "NC"),
    ("goldsboronc", "NC"), ("greensboronc", "NC"), ("greenvillenc", "NC"),
    ("harrisburgnc", "NC"), ("hendersonvliencc", "NC"), ("hendersonvillencc", "NC"),
    ("hendersonvillencc2", "NC"),
    ("hendersonvillencc3", "NC"), ("hendersonvillencc4", "NC"),
    ("hendersonvillencc5", "NC"), ("hendersonvillencc6", "NC"),
    ("hendersonvillencc7", "NC"), ("hendersonvillencc8", "NC"),
    ("hendersonvillencc9", "NC"), ("hendersonvillenc", "NC"),
    ("hickorync", "NC"), ("highpointnc", "NC"),
    ("hollyspringsnc", "NC"), ("huntersvillenc", "NC"),
    ("jacksonvillenc", "NC"), ("kannapolisnc", "NC"),
    ("kernersvillencc", "NC"), ("kernersvillenc", "NC"),
    ("kingnc", "NC"), ("kingsmounnc", "NC"), ("kingsmountainnc", "NC"),
    ("kinstonnnc", "NC"), ("kinstonnc", "NC"),
    ("lenoirncc", "NC"), ("lenoirnc", "NC"),
    ("lexingtonnc", "NC"), ("lincolntonnc", "NC"),
    ("lumbertonnnc", "NC"), ("lumbertonnc", "NC"),
    ("matthewsnc", "NC"), ("minthill nc", "NC"), ("minthillnc", "NC"),
    ("mooresvillencc", "NC"), ("mooresvillenc", "NC"), ("moreheadcitync", "NC"),
    ("morgantonnc", "NC"), ("morrisville nc", "NC"), ("morrisvillenc", "NC"),
    ("mountairy nc", "NC"), ("mountairync", "NC"),
    ("mounthollync", "NC"), ("murfreesboronc", "NC"),
    ("newbernnc", "NC"), ("newtonnc", "NC"),
    ("oxfordnc", "NC"), ("pinehurstnc", "NC"),
    ("raleighnc", "NC"), ("reidsvillencc", "NC"), ("reidsvillenc", "NC"),
    ("rockymountnc", "NC"), ("roxboroncc", "NC"), ("roxboronc", "NC"),
    ("salisburync", "NC"), ("sanfordnc", "NC"),
    ("shelbync", "NC"), ("smithfieldnc", "NC"),
    ("southernpinesncc", "NC"), ("southernpinesnc", "NC"),
    ("statesvllencc", "NC"), ("statesvllenc", "NC"), ("statesvillencc", "NC"),
    ("statesvillenc", "NC"),
    ("swansboncc", "NC"), ("swansboroncc", "NC"), ("swansboronc", "NC"),
    ("tarboroncc", "NC"), ("tarboronc", "NC"),
    ("thomasvillencc", "NC"), ("thomasvillenc", "NC"),
    ("wake forest nc", "NC"), ("wakeforrestncc", "NC"),
    ("wakeforrest ncc", "NC"), ("wakeforestnnc", "NC"),
    ("wakeforrestnc", "NC"), ("wakeForrestnc", "NC"),
    ("wakeForrestncc", "NC"), ("wakeForrestncc2", "NC"),
    ("wakeforestnncc", "NC"), ("wakeforestncc", "NC"),
    ("wakeforest nc", "NC"), ("wakeforest2nc", "NC"),
    ("wakeforest3nc", "NC"), ("wakeforesthc", "NC"),
    ("wakeforestnc", "NC"),
    ("washingtonnc", "NC"), ("whitevllenc", "NC"), ("whitevillencc", "NC"),
    ("whitevillenc", "NC"),
    ("wilkesboroncc", "NC"), ("wilkesboronc", "NC"),
    ("williamstonnc", "NC"), ("wilmingtonnc", "NC"),
    ("wilsonnc", "NC"), ("winston-salemnc", "NC"),
    ("winstonsalemnc", "NC"), ("yadkinvillencc", "NC"),
    ("yadkinvillenc", "NC"), ("zebulonncc", "NC"), ("zebulonnc", "NC"),

    # GA more
    ("acworthga", "GA"), ("albanyga", "GA"), ("alpharettaga", "GA"),
    ("americusga", "GA"), ("athensga", "GA"), ("atlantaga", "GA"),
    ("auburnGA", "GA"), ("aubuernga", "GA"), ("auburnga", "GA"),
    ("augustaga", "GA"), ("austellga", "GA"), ("bainbridgega", "GA"),
    ("ballgroundga", "GA"), ("braseltonaga", "GA"), ("braseltonagg", "GA"),
    ("braseltonagg2", "GA"), ("braseltonga", "GA"),
    ("brookhavenga", "GA"), ("brunswickga", "GA"), ("bufordga", "GA"),
    ("cairoga", "GA"), ("cantonga", "GA"), ("carrollton ga", "GA"),
    ("carrolltonga", "GA"), ("cartersvillega", "GA"), ("chambleega", "GA"),
    ("clevelandga", "GA"), ("collegepark ga", "GA"), ("collegeparkga", "GA"),
    ("columbusga", "GA"), ("conyerga", "GA"), ("conyersga", "GA"),
    ("cordelega", "GA"), ("covingtonga", "GA"), ("cummingga", "GA"),
    ("daltonga", "GA"), ("dawsonvillega", "GA"), ("decaturga", "GA"),
    ("douglasvillega", "GA"), ("dublinag", "GA"), ("dublinagg2", "GA"),
    ("dublinga", "GA"), ("duluthga", "GA"), ("dunwoodyga", "GA"),
    ("eastpointga", "GA"), ("elbertonga", "GA"), ("ellijayvga", "GA"),
    ("ellijayga", "GA"), ("fairburnga", "GA"), ("fayettevilleaga", "GA"),
    ("fayettevillega", "GA"), ("fitzgeraldga", "GA"), ("forsythga", "GA"),
    ("gainesvillega", "GA"), ("griffinga", "GA"), ("grovetownaga", "GA"),
    ("grovetownga", "GA"), ("hamptonga", "GA"), ("hinesvllega", "GA"),
    ("hinesvillega", "GA"), ("hollySpringsGA", "GA"), ("hollyspringsga", "GA"),
    ("johnscreekga", "GA"), ("kennesawga", "GA"), ("lagrangega", "GA"),
    ("lawrencevilleGA", "GA"), ("lawrencevilleGAA", "GA"), ("lawrencevillega", "GA"),
    ("lilburnaga", "GA"), ("lilburnga", "GA"), ("lithiaspringga", "GA"),
    ("lithiaspringsg", "GA"), ("lithiaspringsga", "GA"),
    ("loganvilleaga", "GA"), ("loganvillega", "GA"),
    ("maconga", "GA"), ("mariettaga", "GA"), ("mcdonoughga", "GA"),
    ("milledgevillega", "GA"), ("miltonga", "GA"),
    ("monroega", "GA"), ("moultriegga", "GA"), ("moultrieag", "GA"),
    ("moultriega", "GA"), ("newnanga", "GA"), ("newNANGA", "GA"),
    ("newnanaga", "GA"), ("newnanGA", "GA"), ("newnanag2", "GA"),
    ("newnanag3", "GA"), ("newnanag4", "GA"), ("newnanag5", "GA"),
    ("newnaniaga", "GA"), ("newnang", "GA"), ("newnanaga2", "GA"),
    ("newnanaga3", "GA"), ("newnanaga4", "GA"),
    ("newnanaga5", "GA"), ("newnanag6", "GA"),
    ("neWnanaga", "GA"), ("nEwnanaga", "GA"), ("newnanga", "GA"),
    ("newnanagaa", "GA"), ("newnanagaag", "GA"), ("newnanagaa2", "GA"),
    ("newnanagg", "GA"), ("newnang2", "GA"), ("newnangaga", "GA"),
    ("norcrossGA", "GA"), ("norcrossga", "GA"),
    ("peachtreecityga", "GA"), ("peachtreecornersga", "GA"),
    ("perryga", "GA"), ("poolerga", "GA"), ("richmondhillga", "GA"),
    ("ringgoldga", "GA"), ("romega", "GA"), ("roswellga", "GA"),
    ("sandyspringsga", "GA"), ("savannahga", "GA"), ("smyrnaga", "GA"),
    ("snellvillega", "GA"), ("statesboroga", "GA"), ("stockbridgega", "GA"),
    ("suwaneega", "GA"), ("suwaneega2", "GA"), ("suwanee ga", "GA"),
    ("suwaneeGA", "GA"), ("suwaneeag", "GA"), ("suwaneeagg", "GA"),
    ("suwaneeag2", "GA"), ("suwaneeag3", "GA"), ("suwaneeag4", "GA"),
    ("suwaneeag5", "GA"), ("suwaneeag6", "GA"),
    ("thomastonga", "GA"), ("thomasvillega", "GA"), ("tiftonga", "GA"),
    ("tuckerga", "GA"), ("unioncityga", "GA"),
    ("validostaga", "GA"), ("villaricaga", "GA"), ("winderga", "GA"),
    ("woodstockga", "GA"), ("warnerrobinsga", "GA"),

    # FL more
    ("altamontespringfl", "FL"), ("apalachicola fl", "FL"),
    ("apopkafl", "FL"), ("atlanticbeachfl", "FL"),
    ("aventurafl", "FL"), ("bartowfl", "FL"),
    ("bocaratonfl", "FL"), ("bonitaspringsfl", "FL"),
    ("bradentonfl", "FL"), ("brooksvllefl", "FL"),
    ("capecanaveralfl", "FL"), ("capecoralfl", "FL"),
    ("casselberryfl", "FL"), ("clearwaterfl", "FL"),
    ("clermontfl", "FL"), ("cocoafl", "FL"), ("cocoabeachfl", "FL"),
    ("coconutcreekfl", "FL"), ("coralgablesfl", "FL"),
    ("coralspringsfl", "FL"), ("crestviewfl", "FL"),
    ("dadecityfl", "FL"), ("daytonabeachfl", "FL"),
    ("deerfieldbeachfl", "FL"), ("deltonafl", "FL"),
    ("destinfl", "FL"), ("doralfl", "FL"), ("dunedinfl", "FL"),
    ("edgewaterfl", "FL"), ("englewoodfl", "FL"),
    ("esterofl", "FL"), ("eustisfl", "FL"),
    ("fernandina beachfl", "FL"), ("fernandinabeachfl", "FL"),
    ("fortlauderdalefl", "FL"), ("fortmyersfl", "FL"),
    ("fortmyersbeachfl", "FL"), ("fortpiercefl", "FL"),
    ("fortwaltonbeachfl", "FL"), ("gainesvillefl", "FL"),
    ("greenacresfl", "FL"), ("hallandalebeachfl", "FL"),
    ("hialeahfl", "FL"), ("hollywoodfl", "FL"), ("homesteadfl", "FL"),
    ("jacksonvillefl", "FL"), ("jacksonvillebeachfl", "FL"),
    ("jupiterfl", "FL"), ("kendallfl", "FL"), ("keywestfl", "FL"),
    ("kissimmeefl", "FL"), ("lakecityfl", "FL"),
    ("lakemaryfl", "FL"), ("lakeworthfl", "FL"), ("lakelandfl", "FL"),
    ("largofl", "FL"), ("lauderhillfl", "FL"), ("leesburgfl", "FL"),
    ("margatefl", "FL"), ("melbournefl", "FL"),
    ("miamifl", "FL"), ("miamibeachfl", "FL"), ("miamigardesfl", "FL"),
    ("miamigardenfl", "FL"), ("miamigardesns", "FL"),
    ("miamigardensfl", "FL"), ("miramarfl", "FL"),
    ("mountdorafl", "FL"), ("naplesfl", "FL"),
    ("newportricheyfl", "FL"), ("newsmyrnabeachfl", "FL"),
    ("nicevillefl", "FL"), ("northlauderdalefl", "FL"),
    ("northmiamifl", "FL"), ("northmiamibeachfl", "FL"),
    ("northpalmbeachfl", "FL"), ("northportfl", "FL"),
    ("ocalafl", "FL"), ("ocoeefl", "FL"), ("okeechobeefl", "FL"),
    ("orangecityfl", "FL"), ("orangeparkfl", "FL"),
    ("orlandofl", "FL"), ("ormondbeachfl", "FL"),
    ("oviedofl", "FL"), ("palmbayfl", "FL"),
    ("palmbeachgardenslfl", "FL"), ("palmbeachgardensfl", "FL"),
    ("palmcoastfl", "FL"), ("panamacityfl", "FL"),
    ("panamacitybeachfl", "FL"), ("pensacolafl", "FL"),
    ("pinellasparkfl", "FL"), ("plantationfl", "FL"),
    ("pompanobeachfl", "FL"), ("ponceverafl", "FL"),
    ("portcharlottefl", "FL"), ("portorangefl", "FL"),
    ("portricheyfl", "FL"), ("portstluciefl", "FL"),
    ("rockledgefl", "FL"), ("royalpalmbeachfl", "FL"),
    ("sanfordfl", "FL"), ("sarasotafl", "FL"), ("sebastianfl", "FL"),
    ("seminolefl", "FL"), ("springhillfl", "FL"),
    ("staugustinefl", "FL"), ("stcloudfl", "FL"),
    ("stpetebeachfl", "FL"), ("stpetersburgfl", "FL"),
    ("sunrisefl", "FL"), ("tallahasseefl", "FL"),
    ("tamaracfl", "FL"), ("tampafl", "FL"),
    ("tarponspringsfl", "FL"), ("tamaracfl", "FL"),
    ("tamaracfl2", "FL"), ("tamaracfl3", "FL"),
    ("tamaracfl4", "FL"), ("tamaracfl5", "FL"),
    ("tavresfl", "FL"), ("titusvilefl", "FL"),
    ("titusville fl", "FL"), ("tiutsvilefl", "FL"),
    ("titusvillefl", "FL"), ("venicel", "FL"),
    ("venicefl", "FL"), ("verobeachfl", "FL"),
    ("westmiamifl", "FL"), ("westpalmbeachfl", "FL"),
    ("westonfl", "FL"), ("wildwoodfl", "FL"),
    ("wintergardenfl", "FL"), ("winterhavenfl", "FL"),
    ("winterparkfl", "FL"), ("winterspringsfl", "FL"),
    ("zephyrhillsfl", "FL"),
]


def clean_slug(s):
    return re.sub(r'[^a-z0-9]', '', s.lower())


async def probe_slug(session, slug, semaphore):
    url = f"https://api-east.viewpointcloud.com/v2/{slug}/categories"
    async with semaphore:
        try:
            async with session.get(url, timeout=aiohttp.ClientTimeout(total=10)) as resp:
                if resp.status == 200:
                    try:
                        data = await resp.json()
                        count = len(data.get("data", []))
                        return slug, count
                    except Exception:
                        return slug, 0
                return None
        except Exception:
            return None


async def main():
    # Deduplicate
    seen = set(KNOWN)
    candidates = []
    for raw_slug, state in ROUND4_SLUGS:
        slug = clean_slug(raw_slug)
        if slug and slug not in seen:
            seen.add(slug)
            candidates.append((slug, state))

    print(f"Round 4 candidates: {len(candidates)}")

    semaphore = asyncio.Semaphore(5)
    found = []
    batch_size = 25
    connector = aiohttp.TCPConnector(limit=10, ssl=False)
    headers = {"User-Agent": "Mozilla/5.0 (compatible; permit-research/1.0)"}

    async with aiohttp.ClientSession(connector=connector, headers=headers) as session:
        tasks = [probe_slug(session, slug, semaphore) for slug, _ in candidates]
        slug_state = {slug: state for slug, state in candidates}

        for i in range(0, len(tasks), batch_size):
            batch = tasks[i:i + batch_size]
            results = await asyncio.gather(*batch)
            for r in results:
                if r:
                    slug, count = r
                    state = slug_state.get(slug, "??")
                    found.append({"slug": slug, "state": state, "name": slug, "categories": count})
            await asyncio.sleep(0.5)
            done = min(i + batch_size, len(tasks))
            if (i // batch_size) % 10 == 0 or done == len(tasks):
                print(f"  Progress: {done}/{len(tasks)} | {len(found)} new found")

    print(f"\nRound 4 found {len(found)} additional portals")

    all_portals = list(existing)
    existing_slugs = set(p["slug"] for p in existing)
    for r in found:
        if r["slug"] not in existing_slugs:
            all_portals.append(r)
            existing_slugs.add(r["slug"])

    all_portals.sort(key=lambda x: (x.get("state", ""), x.get("name", "")))
    output_path = "/home/will/permit-api/scripts/opengov_portals.json"
    with open(output_path, "w") as f:
        json.dump(all_portals, f, indent=2)

    print(f"Total portals: {len(all_portals)}")

    if found:
        print("\nNEWLY FOUND IN ROUND 4:")
        for p in sorted(found, key=lambda x: (x["state"], x["slug"])):
            print(f"  {p['slug']:45s} {p['state']:5s} ({p['categories']} cats)")

    return all_portals


if __name__ == "__main__":
    asyncio.run(main())
