#!/usr/bin/env python3
"""
OpenGov Round 2 discovery — targeted candidates based on Round 1 findings.
Key patterns discovered:
- MA towns are very active (tons of hits): just cityname+ma
- RI towns: cityname+ri
- CT towns: cityname+ct
- CO cities: cityname+co
- TX cities: cityname+tx with state suffix
- More state-suffixed variants
"""

import asyncio
import aiohttp
import json
import re

# ── Load already-found slugs ───────────────────────────────────────────────────
with open("/home/will/permit-api/scripts/opengov_portals.json") as f:
    existing = json.load(f)
KNOWN = set(p["slug"] for p in existing)
print(f"Already found: {len(KNOWN)} portals")


# ── Additional candidates (round 2) ───────────────────────────────────────────
ROUND2 = [
    # Massachusetts — virtually every town
    ("abington", "ma", "Abington MA"), ("acushnet", "ma", "Acushnet MA"),
    ("agawam", "ma", "Agawam MA"), ("amesbury", "ma", "Amesbury MA"),
    ("aquinnah", "ma", "Aquinnah MA"), ("arlington", "ma", "Arlington MA"),
    ("ashburnham", "ma", "Ashburnham MA"), ("ashby", "ma", "Ashby MA"),
    ("ashfield", "ma", "Ashfield MA"), ("ashland", "ma", "Ashland MA"),
    ("athol", "ma", "Athol MA"), ("attleboro", "ma", "Attleboro MA"),
    ("auburn", "ma", "Auburn MA"), ("avon", "ma", "Avon MA"),
    ("ayer", "ma", "Ayer MA"), ("barnstable", "ma", "Barnstable MA"),
    ("barre", "ma", "Barre MA"), ("bedford", "ma", "Bedford MA"),
    ("belchertown", "ma", "Belchertown MA"), ("berlin", "ma", "Berlin MA"),
    ("bernardston", "ma", "Bernardston MA"), ("blackstone", "ma", "Blackstone MA"),
    ("blandford", "ma", "Blandford MA"), ("bolton", "ma", "Bolton MA"),
    ("brimfield", "ma", "Brimfield MA"), ("braintree", "ma", "Braintree MA"),
    ("carver", "ma", "Carver MA"), ("charlemont", "ma", "Charlemont MA"),
    ("charlton", "ma", "Charlton MA"), ("chatham", "ma", "Chatham MA"),
    ("chelmsford", "ma", "Chelmsford MA"), ("chelsea", "ma", "Chelsea MA"),
    ("cheshire", "ma", "Cheshire MA"), ("chester", "ma", "Chester MA"),
    ("chesterfield", "ma", "Chesterfield MA"), ("chicopee", "ma", "Chicopee MA"),
    ("chilmark", "ma", "Chilmark MA"), ("clarksburg", "ma", "Clarksburg MA"),
    ("clinton", "ma", "Clinton MA"), ("cohasset", "ma", "Cohasset MA"),
    ("colrain", "ma", "Colrain MA"), ("concord", "ma", "Concord MA"),
    ("conway", "ma", "Conway MA"), ("cummington", "ma", "Cummington MA"),
    ("dalton", "ma", "Dalton MA"), ("danvers", "ma", "Danvers MA"),
    ("dartmouth", "ma", "Dartmouth MA"), ("dedham", "ma", "Dedham MA"),
    ("deerfield", "ma", "Deerfield MA"), ("dennis", "ma", "Dennis MA"),
    ("dighton", "ma", "Dighton MA"), ("douglas", "ma", "Douglas MA"),
    ("dover", "ma", "Dover MA"), ("dracut", "ma", "Dracut MA"),
    ("dunstable", "ma", "Dunstable MA"), ("eastbridgewater", "ma", "East Bridgewater MA"),
    ("eastham", "ma", "Eastham MA"), ("easthampton", "ma", "Easthampton MA"),
    ("easton", "ma", "Easton MA"), ("edgartown", "ma", "Edgartown MA"),
    ("erving", "ma", "Erving MA"), ("essex", "ma", "Essex MA"),
    ("everett", "ma", "Everett MA"), ("fairhaven", "ma", "Fairhaven MA"),
    ("falmouth", "ma", "Falmouth MA"), ("fitchburg", "ma", "Fitchburg MA"),
    ("florida", "ma", "Florida MA"), ("foxborough", "ma", "Foxborough MA"),
    ("foxboro", "ma", "Foxboro MA"), ("framingham", "ma", "Framingham MA"),
    ("franklin", "ma", "Franklin MA"), ("freetown", "ma", "Freetown MA"),
    ("gay head", "ma", "Gay Head MA"), ("gayheadma", "ma", "Gay Head MA"),
    ("georgetown", "ma", "Georgetown MA"), ("gill", "ma", "Gill MA"),
    ("grafton", "ma", "Grafton MA"), ("granby", "ma", "Granby MA"),
    ("granville", "ma", "Granville MA"), ("great barrington", "ma", "Great Barrington MA"),
    ("greatbarringtonma", "ma", "Great Barrington MA"),
    ("greenfield", "ma", "Greenfield MA"), ("groton", "ma", "Groton MA"),
    ("hardwick", "ma", "Hardwick MA"), ("harvard", "ma", "Harvard MA"),
    ("harwich", "ma", "Harwich MA"), ("hatfield", "ma", "Hatfield MA"),
    ("haverhill", "ma", "Haverhill MA"), ("hawley", "ma", "Hawley MA"),
    ("heath", "ma", "Heath MA"), ("hingham", "ma", "Hingham MA"),
    ("hinsdale", "ma", "Hinsdale MA"), ("holbrook", "ma", "Holbrook MA"),
    ("holden", "ma", "Holden MA"), ("holland", "ma", "Holland MA"),
    ("holliston", "ma", "Holliston MA"), ("holyoke", "ma", "Holyoke MA"),
    ("hopdale", "ma", "Hopedale MA"), ("hopedale", "ma", "Hopedale MA"),
    ("hubbardston", "ma", "Hubbardston MA"), ("hull", "ma", "Hull MA"),
    ("huntington", "ma", "Huntington MA"), ("ipswich", "ma", "Ipswich MA"),
    ("kingston", "ma", "Kingston MA"), ("lakeville", "ma", "Lakeville MA"),
    ("lancaster", "ma", "Lancaster MA"), ("lanesborough", "ma", "Lanesborough MA"),
    ("lee", "ma", "Lee MA"), ("leicester", "ma", "Leicester MA"),
    ("lenox", "ma", "Lenox MA"), ("leominster", "ma", "Leominster MA"),
    ("leverett", "ma", "Leverett MA"), ("lincoln", "ma", "Lincoln MA"),
    ("ludlow", "ma", "Ludlow MA"), ("lunenburg", "ma", "Lunenburg MA"),
    ("lynnfield", "ma", "Lynnfield MA"), ("malden", "ma", "Malden MA"),
    ("manchester", "ma", "Manchester MA"), ("mansfield", "ma", "Mansfield MA"),
    ("marshfield", "ma", "Marshfield MA"), ("mashpee", "ma", "Mashpee MA"),
    ("maynard", "ma", "Maynard MA"), ("medford", "ma", "Medford MA"),
    ("medway", "ma", "Medway MA"), ("melrose", "ma", "Melrose MA"),
    ("mendon", "ma", "Mendon MA"), ("merrimac", "ma", "Merrimac MA"),
    ("methuen", "ma", "Methuen MA"), ("middleborough", "ma", "Middleborough MA"),
    ("millis", "ma", "Millis MA"), ("millville", "ma", "Millville MA"),
    ("monson", "ma", "Monson MA"), ("montague", "ma", "Montague MA"),
    ("monterey", "ma", "Monterey MA"), ("montgomery", "ma", "Montgomery MA"),
    ("nahant", "ma", "Nahant MA"), ("nantucket", "ma", "Nantucket MA"),
    ("natick", "ma", "Natick MA"), ("newbury", "ma", "Newbury MA"),
    ("newburyport", "ma", "Newburyport MA"), ("norfolk", "ma", "Norfolk MA"),
    ("northadams", "ma", "North Adams MA"), ("northandover", "ma", "North Andover MA"),
    ("northattleboro", "ma", "North Attleboro MA"),
    ("northborough", "ma", "Northborough MA"),
    ("northbridge", "ma", "Northbridge MA"), ("northbrook", "ma", "Northbrook MA"),
    ("norton", "ma", "Norton MA"), ("norwell", "ma", "Norwell MA"),
    ("norwood", "ma", "Norwood MA"), ("oak bluffs", "ma", "Oak Bluffs MA"),
    ("oakbluffs", "ma", "Oak Bluffs MA"), ("oakham", "ma", "Oakham MA"),
    ("orange", "ma", "Orange MA"), ("orleans", "ma", "Orleans MA"),
    ("otis", "ma", "Otis MA"), ("oxford", "ma", "Oxford MA"),
    ("palmer", "ma", "Palmer MA"), ("paxton", "ma", "Paxton MA"),
    ("pembroke", "ma", "Pembroke MA"), ("pepperell", "ma", "Pepperell MA"),
    ("peru", "ma", "Peru MA"), ("petersham", "ma", "Petersham MA"),
    ("phillipston", "ma", "Phillipston MA"), ("plainfield", "ma", "Plainfield MA"),
    ("plymouth", "ma", "Plymouth MA"), ("plympton", "ma", "Plympton MA"),
    ("princeton", "ma", "Princeton MA"), ("provincetown", "ma", "Provincetown MA"),
    ("randolph", "ma", "Randolph MA"), ("raynham", "ma", "Raynham MA"),
    ("rehoboth", "ma", "Rehoboth MA"), ("revere", "ma", "Revere MA"),
    ("richmond", "ma", "Richmond MA"), ("rochester", "ma", "Rochester MA"),
    ("rockland", "ma", "Rockland MA"), ("rockport", "ma", "Rockport MA"),
    ("rowley", "ma", "Rowley MA"), ("royalston", "ma", "Royalston MA"),
    ("russell", "ma", "Russell MA"), ("rutland", "ma", "Rutland MA"),
    ("salisbury", "ma", "Salisbury MA"), ("sandwich", "ma", "Sandwich MA"),
    ("saugus", "ma", "Saugus MA"), ("savoy", "ma", "Savoy MA"),
    ("scituate", "ma", "Scituate MA"), ("seekonk", "ma", "Seekonk MA"),
    ("sharon", "ma", "Sharon MA"), ("sheffield", "ma", "Sheffield MA"),
    ("shelburne", "ma", "Shelburne MA"), ("sherborn", "ma", "Sherborn MA"),
    ("shutesbury", "ma", "Shutesbury MA"), ("somerset", "ma", "Somerset MA"),
    ("somerville", "ma", "Somerville MA"), ("southampton", "ma", "Southampton MA"),
    ("southborough", "ma", "Southborough MA"), ("southbridge", "ma", "Southbridge MA"),
    ("southwick", "ma", "Southwick MA"), ("spencer", "ma", "Spencer MA"),
    ("springfield", "ma", "Springfield MA"), ("sterling", "ma", "Sterling MA"),
    ("stockbridge", "ma", "Stockbridge MA"), ("stoneham", "ma", "Stoneham MA"),
    ("stoughton", "ma", "Stoughton MA"), ("stow", "ma", "Stow MA"),
    ("sturbridge", "ma", "Sturbridge MA"), ("sudbury", "ma", "Sudbury MA"),
    ("sunderland", "ma", "Sunderland MA"), ("sutton", "ma", "Sutton MA"),
    ("swansea", "ma", "Swansea MA"), ("templeton", "ma", "Templeton MA"),
    ("tewksbury", "ma", "Tewksbury MA"), ("tisbury", "ma", "Tisbury MA"),
    ("tolland", "ma", "Tolland MA"), ("topsfield", "ma", "Topsfield MA"),
    ("townsend", "ma", "Townsend MA"), ("truro", "ma", "Truro MA"),
    ("tyngsborough", "ma", "Tyngsborough MA"), ("tyringham", "ma", "Tyringham MA"),
    ("upton", "ma", "Upton MA"), ("uxbridge", "ma", "Uxbridge MA"),
    ("wakefield", "ma", "Wakefield MA"), ("wales", "ma", "Wales MA"),
    ("walpole", "ma", "Walpole MA"), ("waltham", "ma", "Waltham MA"),
    ("ware", "ma", "Ware MA"), ("wareham", "ma", "Wareham MA"),
    ("warren", "ma", "Warren MA"), ("warwick", "ma", "Warwick MA"),
    ("washington", "ma", "Washington MA"), ("watertown", "ma", "Watertown MA"),
    ("wayland", "ma", "Wayland MA"), ("webster", "ma", "Webster MA"),
    ("wellesley", "ma", "Wellesley MA"), ("wellfleet", "ma", "Wellfleet MA"),
    ("wendell", "ma", "Wendell MA"), ("wenham", "ma", "Wenham MA"),
    ("westborough", "ma", "Westborough MA"), ("westboylston", "ma", "West Boylston MA"),
    ("westbridgewater", "ma", "West Bridgewater MA"), ("westfield", "ma", "Westfield MA"),
    ("westford", "ma", "Westford MA"), ("westhampton", "ma", "Westhampton MA"),
    ("weston", "ma", "Weston MA"), ("westport", "ma", "Westport MA"),
    ("weymouth", "ma", "Weymouth MA"), ("whately", "ma", "Whately MA"),
    ("whitman", "ma", "Whitman MA"), ("wilbraham", "ma", "Wilbraham MA"),
    ("williamsburg", "ma", "Williamsburg MA"), ("wilmington", "ma", "Wilmington MA"),
    ("winchendon", "ma", "Winchendon MA"), ("windsor", "ma", "Windsor MA"),
    ("winthrop", "ma", "Winthrop MA"), ("woburn", "ma", "Woburn MA"),
    ("worthington", "ma", "Worthington MA"), ("wrentham", "ma", "Wrentham MA"),
    ("yarmouth", "ma", "Yarmouth MA"),

    # Rhode Island — all towns
    ("burrillville", "ri", "Burrillville RI"), ("charlestown", "ri", "Charlestown RI"),
    ("coventry", "ri", "Coventry RI"), ("cranston", "ri", "Cranston RI"),
    ("cumberland", "ri", "Cumberland RI"), ("east greenwich", "ri", "East Greenwich RI"),
    ("eastgreenwich", "ri", "East Greenwich RI"),
    ("east providence", "ri", "East Providence RI"),
    ("eastprovidence", "ri", "East Providence RI"),
    ("exeter", "ri", "Exeter RI"), ("foster", "ri", "Foster RI"),
    ("glocester", "ri", "Glocester RI"), ("hopkinton", "ri", "Hopkinton RI"),
    ("jamestown", "ri", "Jamestown RI"), ("johnston", "ri", "Johnston RI"),
    ("lincoln", "ri", "Lincoln RI"), ("little compton", "ri", "Little Compton RI"),
    ("littlecompton", "ri", "Little Compton RI"),
    ("middletown", "ri", "Middletown RI"), ("narragansett", "ri", "Narragansett RI"),
    ("new shoreham", "ri", "New Shoreham RI"), ("newshoreham", "ri", "New Shoreham RI"),
    ("newport", "ri", "Newport RI"), ("north kingstown", "ri", "North Kingstown RI"),
    ("northkingstown", "ri", "North Kingstown RI"),
    ("north providence", "ri", "North Providence RI"),
    ("northprovidence", "ri", "North Providence RI"),
    ("north smithfield", "ri", "North Smithfield RI"),
    ("northsmithfield", "ri", "North Smithfield RI"),
    ("pawtucket", "ri", "Pawtucket RI"), ("portsmouth", "ri", "Portsmouth RI"),
    ("providence", "ri", "Providence RI"), ("richmond", "ri", "Richmond RI"),
    ("scituate", "ri", "Scituate RI"), ("smithfield", "ri", "Smithfield RI"),
    ("south kingstown", "ri", "South Kingstown RI"),
    ("southkingstown", "ri", "South Kingstown RI"),
    ("tiverton", "ri", "Tiverton RI"), ("warren", "ri", "Warren RI"),
    ("warwick", "ri", "Warwick RI"), ("west greenwich", "ri", "West Greenwich RI"),
    ("westgreenwich", "ri", "West Greenwich RI"),
    ("west warwick", "ri", "West Warwick RI"), ("westwarwick", "ri", "West Warwick RI"),
    ("westerly", "ri", "Westerly RI"), ("woonsocket", "ri", "Woonsocket RI"),

    # Connecticut — more towns
    ("andover", "ct", "Andover CT"), ("ansonia", "ct", "Ansonia CT"),
    ("ashford", "ct", "Ashford CT"), ("beacon falls", "ct", "Beacon Falls CT"),
    ("beaconfalls", "ct", "Beacon Falls CT"), ("berlin", "ct", "Berlin CT"),
    ("bethany", "ct", "Bethany CT"), ("bethel", "ct", "Bethel CT"),
    ("bethlehem", "ct", "Bethlehem CT"), ("bolton", "ct", "Bolton CT"),
    ("bozrah", "ct", "Bozrah CT"), ("bridgeport", "ct", "Bridgeport CT"),
    ("bridgewater", "ct", "Bridgewater CT"), ("brooklyn", "ct", "Brooklyn CT"),
    ("burlington", "ct", "Burlington CT"), ("canaan", "ct", "Canaan CT"),
    ("canton", "ct", "Canton CT"), ("chaplin", "ct", "Chaplin CT"),
    ("colchester", "ct", "Colchester CT"), ("colebrook", "ct", "Colebrook CT"),
    ("columbia", "ct", "Columbia CT"), ("cornwall", "ct", "Cornwall CT"),
    ("coventry", "ct", "Coventry CT"), ("cromwell", "ct", "Cromwell CT"),
    ("deep river", "ct", "Deep River CT"), ("deepriver", "ct", "Deep River CT"),
    ("derby", "ct", "Derby CT"), ("durham", "ct", "Durham CT"),
    ("east granby", "ct", "East Granby CT"), ("eastgranby", "ct", "East Granby CT"),
    ("east haddam", "ct", "East Haddam CT"), ("easthaddam", "ct", "East Haddam CT"),
    ("east hampton", "ct", "East Hampton CT"), ("easthampton", "ct", "East Hampton CT"),
    ("east hartford", "ct", "East Hartford CT"), ("easthartford", "ct", "East Hartford CT"),
    ("east haven", "ct", "East Haven CT"), ("easthaven", "ct", "East Haven CT"),
    ("east lyme", "ct", "East Lyme CT"), ("eastlyme", "ct", "East Lyme CT"),
    ("east windsor", "ct", "East Windsor CT"), ("eastwindsor", "ct", "East Windsor CT"),
    ("ellington", "ct", "Ellington CT"), ("essex", "ct", "Essex CT"),
    ("franklin", "ct", "Franklin CT"), ("glastonbury", "ct", "Glastonbury CT"),
    ("goshen", "ct", "Goshen CT"), ("granby", "ct", "Granby CT"),
    ("greenwich", "ct", "Greenwich CT"), ("griswold", "ct", "Griswold CT"),
    ("groton", "ct", "Groton CT"), ("guilford", "ct", "Guilford CT"),
    ("haddam", "ct", "Haddam CT"), ("hartford", "ct", "Hartford CT"),
    ("harwinton", "ct", "Harwinton CT"), ("hebron", "ct", "Hebron CT"),
    ("kent", "ct", "Kent CT"), ("killingly", "ct", "Killingly CT"),
    ("killingworth", "ct", "Killingworth CT"), ("lebanon", "ct", "Lebanon CT"),
    ("ledyard", "ct", "Ledyard CT"), ("lisbon", "ct", "Lisbon CT"),
    ("litchfield", "ct", "Litchfield CT"), ("lyme", "ct", "Lyme CT"),
    ("manchester", "ct", "Manchester CT"), ("mansfield", "ct", "Mansfield CT"),
    ("marlborough", "ct", "Marlborough CT"), ("meriden", "ct", "Meriden CT"),
    ("middlebury", "ct", "Middlebury CT"), ("middlefield", "ct", "Middlefield CT"),
    ("middletown", "ct", "Middletown CT"), ("milford", "ct", "Milford CT"),
    ("monroe", "ct", "Monroe CT"), ("montville", "ct", "Montville CT"),
    ("morris", "ct", "Morris CT"), ("naugatuck", "ct", "Naugatuck CT"),
    ("new britain", "ct", "New Britain CT"), ("new canaan", "ct", "New Canaan CT"),
    ("new fairfield", "ct", "New Fairfield CT"), ("new hartford", "ct", "New Hartford CT"),
    ("newhartford", "ct", "New Hartford CT"),
    ("new haven", "ct", "New Haven CT"), ("new london", "ct", "New London CT"),
    ("newlondon", "ct", "New London CT"),
    ("new milford", "ct", "New Milford CT"), ("newtown", "ct", "Newtown CT"),
    ("north branford", "ct", "North Branford CT"),
    ("northbranford", "ct", "North Branford CT"),
    ("north canaan", "ct", "North Canaan CT"), ("northcanaan", "ct", "North Canaan CT"),
    ("north haven", "ct", "North Haven CT"), ("northhaven", "ct", "North Haven CT"),
    ("north stonington", "ct", "North Stonington CT"),
    ("northstonington", "ct", "North Stonington CT"),
    ("norwalk", "ct", "Norwalk CT"), ("norwich", "ct", "Norwich CT"),
    ("old lyme", "ct", "Old Lyme CT"), ("oldlyme", "ct", "Old Lyme CT"),
    ("old saybrook", "ct", "Old Saybrook CT"), ("oldsaybrook", "ct", "Old Saybrook CT"),
    ("orange", "ct", "Orange CT"), ("oxford", "ct", "Oxford CT"),
    ("plainfield", "ct", "Plainfield CT"), ("plainville", "ct", "Plainville CT"),
    ("plymouth", "ct", "Plymouth CT"), ("pomfret", "ct", "Pomfret CT"),
    ("portland", "ct", "Portland CT"), ("preston", "ct", "Preston CT"),
    ("prospect", "ct", "Prospect CT"), ("putnam", "ct", "Putnam CT"),
    ("redding", "ct", "Redding CT"), ("rocky hill", "ct", "Rocky Hill CT"),
    ("roxbury", "ct", "Roxbury CT"), ("salem", "ct", "Salem CT"),
    ("salisbury", "ct", "Salisbury CT"), ("scotland", "ct", "Scotland CT"),
    ("seymour", "ct", "Seymour CT"), ("sharon", "ct", "Sharon CT"),
    ("shelton", "ct", "Shelton CT"), ("sherman", "ct", "Sherman CT"),
    ("simsbury", "ct", "Simsbury CT"), ("somers", "ct", "Somers CT"),
    ("south windsor", "ct", "South Windsor CT"), ("southbury", "ct", "Southbury CT"),
    ("southington", "ct", "Southington CT"), ("sprague", "ct", "Sprague CT"),
    ("stafford", "ct", "Stafford CT"), ("stamford", "ct", "Stamford CT"),
    ("sterling", "ct", "Sterling CT"), ("stonington", "ct", "Stonington CT"),
    ("stratford", "ct", "Stratford CT"), ("suffield", "ct", "Suffield CT"),
    ("thomaston", "ct", "Thomaston CT"), ("thompson", "ct", "Thompson CT"),
    ("tolland", "ct", "Tolland CT"), ("torrington", "ct", "Torrington CT"),
    ("trumbull", "ct", "Trumbull CT"), ("union", "ct", "Union CT"),
    ("vernon", "ct", "Vernon CT"), ("voluntown", "ct", "Voluntown CT"),
    ("wallingford", "ct", "Wallingford CT"), ("waterbury", "ct", "Waterbury CT"),
    ("waterford", "ct", "Waterford CT"), ("watertown", "ct", "Watertown CT"),
    ("west hartford", "ct", "West Hartford CT"), ("westhartford", "ct", "West Hartford CT"),
    ("west haven", "ct", "West Haven CT"), ("westhaven", "ct", "West Haven CT"),
    ("westbrook", "ct", "Westbrook CT"), ("weston", "ct", "Weston CT"),
    ("westport", "ct", "Westport CT"), ("wethersfield", "ct", "Wethersfield CT"),
    ("windham", "ct", "Windham CT"), ("windsor", "ct", "Windsor CT"),
    ("windsor locks", "ct", "Windsor Locks CT"), ("windsorlocks", "ct", "Windsor Locks CT"),
    ("wolcott", "ct", "Wolcott CT"), ("woodbridge", "ct", "Woodbridge CT"),
    ("woodbury", "ct", "Woodbury CT"), ("woodstock", "ct", "Woodstock CT"),

    # New Hampshire — all towns
    ("acworth", "nh", "Acworth NH"), ("albany", "nh", "Albany NH"),
    ("alexandria", "nh", "Alexandria NH"), ("allenstown", "nh", "Allenstown NH"),
    ("alstead", "nh", "Alstead NH"), ("alton", "nh", "Alton NH"),
    ("amherst", "nh", "Amherst NH"), ("andover", "nh", "Andover NH"),
    ("antrim", "nh", "Antrim NH"), ("atkinson", "nh", "Atkinson NH"),
    ("auburn", "nh", "Auburn NH"), ("barrington", "nh", "Barrington NH"),
    ("bartlett", "nh", "Bartlett NH"), ("bath", "nh", "Bath NH"),
    ("bedford", "nh", "Bedford NH"), ("belmont", "nh", "Belmont NH"),
    ("bennington", "nh", "Bennington NH"), ("benton", "nh", "Benton NH"),
    ("berlin", "nh", "Berlin NH"), ("bethlehem", "nh", "Bethlehem NH"),
    ("boscawen", "nh", "Boscawen NH"), ("bow", "nh", "Bow NH"),
    ("bradford", "nh", "Bradford NH"), ("brentwood", "nh", "Brentwood NH"),
    ("bridgewater", "nh", "Bridgewater NH"), ("bristol", "nh", "Bristol NH"),
    ("brookfield", "nh", "Brookfield NH"), ("brookline", "nh", "Brookline NH"),
    ("cambridge", "nh", "Cambridge NH"), ("campton", "nh", "Campton NH"),
    ("canaan", "nh", "Canaan NH"), ("candia", "nh", "Candia NH"),
    ("canterbury", "nh", "Canterbury NH"), ("carroll", "nh", "Carroll NH"),
    ("center harbor", "nh", "Center Harbor NH"), ("charlestown", "nh", "Charlestown NH"),
    ("chatham", "nh", "Chatham NH"), ("chester", "nh", "Chester NH"),
    ("chesterfield", "nh", "Chesterfield NH"), ("chichester", "nh", "Chichester NH"),
    ("claremont", "nh", "Claremont NH"), ("clarksville", "nh", "Clarksville NH"),
    ("colebrook", "nh", "Colebrook NH"), ("columbia", "nh", "Columbia NH"),
    ("concord", "nh", "Concord NH"), ("conway", "nh", "Conway NH"),
    ("cornish", "nh", "Cornish NH"), ("dalton", "nh", "Dalton NH"),
    ("danbury", "nh", "Danbury NH"), ("danville", "nh", "Danville NH"),
    ("deerfield", "nh", "Deerfield NH"), ("deering", "nh", "Deering NH"),
    ("derry", "nh", "Derry NH"), ("dover", "nh", "Dover NH"),
    ("dublin", "nh", "Dublin NH"), ("dummer", "nh", "Dummer NH"),
    ("dunbarton", "nh", "Dunbarton NH"), ("durham", "nh", "Durham NH"),
    ("east kingston", "nh", "East Kingston NH"), ("eastkingston", "nh", "East Kingston NH"),
    ("eaton", "nh", "Eaton NH"), ("effingham", "nh", "Effingham NH"),
    ("ellsworth", "nh", "Ellsworth NH"), ("enfield", "nh", "Enfield NH"),
    ("epping", "nh", "Epping NH"), ("epsom", "nh", "Epsom NH"),
    ("errol", "nh", "Errol NH"), ("exeter", "nh", "Exeter NH"),
    ("farmington", "nh", "Farmington NH"), ("fitzwilliam", "nh", "Fitzwilliam NH"),
    ("francestown", "nh", "Francestown NH"), ("franconia", "nh", "Franconia NH"),
    ("freedom", "nh", "Freedom NH"), ("fremont", "nh", "Fremont NH"),
    ("gilford", "nh", "Gilford NH"), ("gilmanton", "nh", "Gilmanton NH"),
    ("gilsum", "nh", "Gilsum NH"), ("goffstown", "nh", "Goffstown NH"),
    ("gorham", "nh", "Gorham NH"), ("goshen", "nh", "Goshen NH"),
    ("grafton", "nh", "Grafton NH"), ("grantham", "nh", "Grantham NH"),
    ("greenfield", "nh", "Greenfield NH"), ("greenland", "nh", "Greenland NH"),
    ("greenville", "nh", "Greenville NH"), ("groton", "nh", "Groton NH"),
    ("hampstead", "nh", "Hampstead NH"), ("hampton", "nh", "Hampton NH"),
    ("hampton falls", "nh", "Hampton Falls NH"), ("hamptonfall", "nh", "Hampton Falls NH"),
    ("hancock", "nh", "Hancock NH"), ("hanover", "nh", "Hanover NH"),
    ("harrisville", "nh", "Harrisville NH"), ("hart location", "nh", "Hart Location NH"),
    ("haverhill", "nh", "Haverhill NH"), ("hedgehog", "nh", "Hedgehog NH"),
    ("henniker", "nh", "Henniker NH"), ("hill", "nh", "Hill NH"),
    ("hillsborough", "nh", "Hillsborough NH"), ("hinsdale", "nh", "Hinsdale NH"),
    ("holderness", "nh", "Holderness NH"), ("hollis", "nh", "Hollis NH"),
    ("hooksett", "nh", "Hooksett NH"), ("hopkinton", "nh", "Hopkinton NH"),
    ("hudson", "nh", "Hudson NH"), ("jackson", "nh", "Jackson NH"),
    ("jaffrey", "nh", "Jaffrey NH"), ("jefferson", "nh", "Jefferson NH"),
    ("keene", "nh", "Keene NH"), ("kensington", "nh", "Kensington NH"),
    ("kingston", "nh", "Kingston NH"), ("laconia", "nh", "Laconia NH"),
    ("lancaster", "nh", "Lancaster NH"), ("langdon", "nh", "Langdon NH"),
    ("lempster", "nh", "Lempster NH"), ("lincoln", "nh", "Lincoln NH"),
    ("lisbon", "nh", "Lisbon NH"), ("litchfield", "nh", "Litchfield NH"),
    ("littleton", "nh", "Littleton NH"), ("londonderry", "nh", "Londonderry NH"),
    ("loudon", "nh", "Loudon NH"), ("lyman", "nh", "Lyman NH"),
    ("lyme", "nh", "Lyme NH"), ("lyndeborough", "nh", "Lyndeborough NH"),
    ("madbury", "nh", "Madbury NH"), ("madison", "nh", "Madison NH"),
    ("manchester", "nh", "Manchester NH"), ("marlborough", "nh", "Marlborough NH"),
    ("marlow", "nh", "Marlow NH"), ("mason", "nh", "Mason NH"),
    ("meredith", "nh", "Meredith NH"), ("merrimack", "nh", "Merrimack NH"),
    ("middleton", "nh", "Middleton NH"), ("milan", "nh", "Milan NH"),
    ("milford", "nh", "Milford NH"), ("milton", "nh", "Milton NH"),
    ("monroe", "nh", "Monroe NH"), ("mont vernon", "nh", "Mont Vernon NH"),
    ("moultonborough", "nh", "Moultonborough NH"), ("nashua", "nh", "Nashua NH"),
    ("nelson", "nh", "Nelson NH"), ("new boston", "nh", "New Boston NH"),
    ("newboston", "nh", "New Boston NH"), ("new castle", "nh", "New Castle NH"),
    ("newcastle", "nh", "New Castle NH"), ("new durham", "nh", "New Durham NH"),
    ("newdurham", "nh", "New Durham NH"), ("new hampton", "nh", "New Hampton NH"),
    ("newhampton", "nh", "New Hampton NH"), ("new ipswich", "nh", "New Ipswich NH"),
    ("newipswich", "nh", "New Ipswich NH"), ("new london", "nh", "New London NH"),
    ("newlondon", "nh", "New London NH"), ("newbury", "nh", "Newbury NH"),
    ("newfields", "nh", "Newfields NH"), ("newington", "nh", "Newington NH"),
    ("newmarket", "nh", "Newmarket NH"), ("newport", "nh", "Newport NH"),
    ("newton", "nh", "Newton NH"), ("north hampton", "nh", "North Hampton NH"),
    ("northhampton", "nh", "North Hampton NH"), ("northfield", "nh", "Northfield NH"),
    ("northumberland", "nh", "Northumberland NH"),
    ("northwood", "nh", "Northwood NH"), ("nottingham", "nh", "Nottingham NH"),
    ("orange", "nh", "Orange NH"), ("orford", "nh", "Orford NH"),
    ("ossipee", "nh", "Ossipee NH"), ("pelham", "nh", "Pelham NH"),
    ("pembroke", "nh", "Pembroke NH"), ("peterborough", "nh", "Peterborough NH"),
    ("piermont", "nh", "Piermont NH"), ("pittsburg", "nh", "Pittsburg NH"),
    ("pittsfield", "nh", "Pittsfield NH"), ("plaistow", "nh", "Plaistow NH"),
    ("plymouth", "nh", "Plymouth NH"), ("portsmouth", "nh", "Portsmouth NH"),
    ("raymond", "nh", "Raymond NH"), ("richmond", "nh", "Richmond NH"),
    ("rindge", "nh", "Rindge NH"), ("rochester", "nh", "Rochester NH"),
    ("rollinsford", "nh", "Rollinsford NH"), ("rumney", "nh", "Rumney NH"),
    ("rye", "nh", "Rye NH"), ("salem", "nh", "Salem NH"),
    ("salisbury", "nh", "Salisbury NH"), ("sanbornton", "nh", "Sanbornton NH"),
    ("sandown", "nh", "Sandown NH"), ("sandwich", "nh", "Sandwich NH"),
    ("seabrook", "nh", "Seabrook NH"), ("sharon", "nh", "Sharon NH"),
    ("somersworth", "nh", "Somersworth NH"), ("south hampton", "nh", "South Hampton NH"),
    ("southhampton", "nh", "South Hampton NH"), ("springfield", "nh", "Springfield NH"),
    ("stark", "nh", "Stark NH"), ("stewartstown", "nh", "Stewartstown NH"),
    ("stoddard", "nh", "Stoddard NH"), ("strafford", "nh", "Strafford NH"),
    ("stratford", "nh", "Stratford NH"), ("stratham", "nh", "Stratham NH"),
    ("sugar hill", "nh", "Sugar Hill NH"), ("sullivan", "nh", "Sullivan NH"),
    ("surry", "nh", "Surry NH"), ("sutton", "nh", "Sutton NH"),
    ("swanzey", "nh", "Swanzey NH"), ("tamworth", "nh", "Tamworth NH"),
    ("temple", "nh", "Temple NH"), ("thornton", "nh", "Thornton NH"),
    ("tilton", "nh", "Tilton NH"), ("troy", "nh", "Troy NH"),
    ("tuftonboro", "nh", "Tuftonboro NH"), ("unity", "nh", "Unity NH"),
    ("wakefield", "nh", "Wakefield NH"), ("walpole", "nh", "Walpole NH"),
    ("warner", "nh", "Warner NH"), ("warren", "nh", "Warren NH"),
    ("washington", "nh", "Washington NH"), ("waterville valley", "nh", "Waterville Valley NH"),
    ("weare", "nh", "Weare NH"), ("webster", "nh", "Webster NH"),
    ("westmoreland", "nh", "Westmoreland NH"), ("whitefield", "nh", "Whitefield NH"),
    ("wilmot", "nh", "Wilmot NH"), ("wilton", "nh", "Wilton NH"),
    ("winchester", "nh", "Winchester NH"), ("windham", "nh", "Windham NH"),
    ("windsor", "nh", "Windsor NH"), ("wolfeboro", "nh", "Wolfeboro NH"),
    ("woodstock", "nh", "Woodstock NH"),

    # Vermont — all towns
    ("addison", "vt", "Addison VT"), ("albany", "vt", "Albany VT"),
    ("alburg", "vt", "Alburg VT"), ("andover", "vt", "Andover VT"),
    ("arlington", "vt", "Arlington VT"), ("athens", "vt", "Athens VT"),
    ("bakersfield", "vt", "Bakersfield VT"), ("baltimore", "vt", "Baltimore VT"),
    ("barnard", "vt", "Barnard VT"), ("barnet", "vt", "Barnet VT"),
    ("barre", "vt", "Barre VT"), ("barton", "vt", "Barton VT"),
    ("belvidere", "vt", "Belvidere VT"), ("bennington", "vt", "Bennington VT"),
    ("benson", "vt", "Benson VT"), ("berkshire", "vt", "Berkshire VT"),
    ("berlin", "vt", "Berlin VT"), ("bethel", "vt", "Bethel VT"),
    ("bloomfield", "vt", "Bloomfield VT"), ("bolton", "vt", "Bolton VT"),
    ("bradford", "vt", "Bradford VT"), ("braintree", "vt", "Braintree VT"),
    ("brandon", "vt", "Brandon VT"), ("brattleboro", "vt", "Brattleboro VT"),
    ("bridgewater", "vt", "Bridgewater VT"), ("bridport", "vt", "Bridport VT"),
    ("brighton", "vt", "Brighton VT"), ("bristol", "vt", "Bristol VT"),
    ("brookfield", "vt", "Brookfield VT"), ("brookline", "vt", "Brookline VT"),
    ("brownington", "vt", "Brownington VT"), ("brunswick", "vt", "Brunswick VT"),
    ("burke", "vt", "Burke VT"), ("burlington", "vt", "Burlington VT"),
    ("cabot", "vt", "Cabot VT"), ("calais", "vt", "Calais VT"),
    ("cambridge", "vt", "Cambridge VT"), ("canaan", "vt", "Canaan VT"),
    ("castleton", "vt", "Castleton VT"), ("cavendish", "vt", "Cavendish VT"),
    ("charleston", "vt", "Charleston VT"), ("charlotte", "vt", "Charlotte VT"),
    ("chelsea", "vt", "Chelsea VT"), ("chester", "vt", "Chester VT"),
    ("chittenden", "vt", "Chittenden VT"), ("colchester", "vt", "Colchester VT"),
    ("concord", "vt", "Concord VT"), ("corinth", "vt", "Corinth VT"),
    ("coventry", "vt", "Coventry VT"), ("craftsbury", "vt", "Craftsbury VT"),
    ("danby", "vt", "Danby VT"), ("danville", "vt", "Danville VT"),
    ("derby", "vt", "Derby VT"), ("dorset", "vt", "Dorset VT"),
    ("dover", "vt", "Dover VT"), ("dummerston", "vt", "Dummerston VT"),
    ("duxbury", "vt", "Duxbury VT"), ("east montpelier", "vt", "East Montpelier VT"),
    ("eastmontpelier", "vt", "East Montpelier VT"),
    ("eden", "vt", "Eden VT"), ("elmore", "vt", "Elmore VT"),
    ("enosburgh", "vt", "Enosburgh VT"), ("essex", "vt", "Essex VT"),
    ("fairfax", "vt", "Fairfax VT"), ("fairfield", "vt", "Fairfield VT"),
    ("fair haven", "vt", "Fair Haven VT"), ("fairhaven", "vt", "Fair Haven VT"),
    ("fayston", "vt", "Fayston VT"), ("ferrisburgh", "vt", "Ferrisburgh VT"),
    ("fletcher", "vt", "Fletcher VT"), ("franklin", "vt", "Franklin VT"),
    ("Georgia", "vt", "Georgia VT"), ("glover", "vt", "Glover VT"),
    ("goshen", "vt", "Goshen VT"), ("grafton", "vt", "Grafton VT"),
    ("granby", "vt", "Granby VT"), ("grand isle", "vt", "Grand Isle VT"),
    ("grandisle", "vt", "Grand Isle VT"), ("granville", "vt", "Granville VT"),
    ("greensboro", "vt", "Greensboro VT"), ("groton", "vt", "Groton VT"),
    ("guildhall", "vt", "Guildhall VT"), ("guilford", "vt", "Guilford VT"),
    ("halifax", "vt", "Halifax VT"), ("hancock", "vt", "Hancock VT"),
    ("hardwick", "vt", "Hardwick VT"), ("hartford", "vt", "Hartford VT"),
    ("hartland", "vt", "Hartland VT"), ("highgate", "vt", "Highgate VT"),
    ("hinesburg", "vt", "Hinesburg VT"), ("holland", "vt", "Holland VT"),
    ("hubbardton", "vt", "Hubbardton VT"), ("huntington", "vt", "Huntington VT"),
    ("hyde park", "vt", "Hyde Park VT"), ("hydepark", "vt", "Hyde Park VT"),
    ("ira", "vt", "Ira VT"), ("irasburg", "vt", "Irasburg VT"),
    ("isle la motte", "vt", "Isle La Motte VT"),
    ("jamaica", "vt", "Jamaica VT"), ("johnson", "vt", "Johnson VT"),
    ("kirby", "vt", "Kirby VT"), ("landgrove", "vt", "Landgrove VT"),
    ("leicester", "vt", "Leicester VT"), ("lemington", "vt", "Lemington VT"),
    ("lincoln", "vt", "Lincoln VT"), ("londonderry", "vt", "Londonderry VT"),
    ("lowell", "vt", "Lowell VT"), ("ludlow", "vt", "Ludlow VT"),
    ("lunenburg", "vt", "Lunenburg VT"), ("lyndon", "vt", "Lyndon VT"),
    ("maidstone", "vt", "Maidstone VT"), ("manchester", "vt", "Manchester VT"),
    ("marlboro", "vt", "Marlboro VT"), ("marshfield", "vt", "Marshfield VT"),
    ("mendon", "vt", "Mendon VT"), ("middlebury", "vt", "Middlebury VT"),
    ("middlesex", "vt", "Middlesex VT"), ("middletown springs", "vt", "Middletown Springs VT"),
    ("milton", "vt", "Milton VT"), ("monkton", "vt", "Monkton VT"),
    ("montpelier", "vt", "Montpelier VT"), ("moretown", "vt", "Moretown VT"),
    ("morgan", "vt", "Morgan VT"), ("morristown", "vt", "Morristown VT"),
    ("mount holly", "vt", "Mount Holly VT"), ("mount tabor", "vt", "Mount Tabor VT"),
    ("newbury", "vt", "Newbury VT"), ("newfane", "vt", "Newfane VT"),
    ("newport", "vt", "Newport VT"), ("north hero", "vt", "North Hero VT"),
    ("northhero", "vt", "North Hero VT"), ("northfield", "vt", "Northfield VT"),
    ("norton", "vt", "Norton VT"), ("norwich", "vt", "Norwich VT"),
    ("orange", "vt", "Orange VT"), ("orwell", "vt", "Orwell VT"),
    ("panton", "vt", "Panton VT"), ("pawlet", "vt", "Pawlet VT"),
    ("peacham", "vt", "Peacham VT"), ("peru", "vt", "Peru VT"),
    ("pittsfield", "vt", "Pittsfield VT"), ("pittsford", "vt", "Pittsford VT"),
    ("plainfield", "vt", "Plainfield VT"), ("plymouth", "vt", "Plymouth VT"),
    ("pomfret", "vt", "Pomfret VT"), ("poultney", "vt", "Poultney VT"),
    ("pownal", "vt", "Pownal VT"), ("proctor", "vt", "Proctor VT"),
    ("putney", "vt", "Putney VT"), ("randolph", "vt", "Randolph VT"),
    ("reading", "vt", "Reading VT"), ("readsboro", "vt", "Readsboro VT"),
    ("richford", "vt", "Richford VT"), ("richmond", "vt", "Richmond VT"),
    ("ripton", "vt", "Ripton VT"), ("rochester", "vt", "Rochester VT"),
    ("rockingham", "vt", "Rockingham VT"), ("roxbury", "vt", "Roxbury VT"),
    ("royalton", "vt", "Royalton VT"), ("rupert", "vt", "Rupert VT"),
    ("rutland", "vt", "Rutland VT"), ("ryegate", "vt", "Ryegate VT"),
    ("saint albans", "vt", "Saint Albans VT"), ("stalbans", "vt", "St Albans VT"),
    ("saint george", "vt", "Saint George VT"),
    ("saint johnsbury", "vt", "Saint Johnsbury VT"),
    ("salisbury", "vt", "Salisbury VT"), ("sandgate", "vt", "Sandgate VT"),
    ("searsburg", "vt", "Searsburg VT"), ("shaftsbury", "vt", "Shaftsbury VT"),
    ("sharon", "vt", "Sharon VT"), ("sheffield", "vt", "Sheffield VT"),
    ("shelburne", "vt", "Shelburne VT"), ("sheldon", "vt", "Sheldon VT"),
    ("shoreham", "vt", "Shoreham VT"), ("shrewsbury", "vt", "Shrewsbury VT"),
    ("south burlington", "vt", "South Burlington VT"),
    ("southburlington", "vt", "South Burlington VT"),
    ("south hero", "vt", "South Hero VT"), ("southhero", "vt", "South Hero VT"),
    ("springfield", "vt", "Springfield VT"), ("st johnsbury", "vt", "St. Johnsbury VT"),
    ("stjohnsbury", "vt", "St. Johnsbury VT"),
    ("stamford", "vt", "Stamford VT"), ("starksboro", "vt", "Starksboro VT"),
    ("stockbridge", "vt", "Stockbridge VT"), ("stowe", "vt", "Stowe VT"),
    ("strafford", "vt", "Strafford VT"), ("stratton", "vt", "Stratton VT"),
    ("sudbury", "vt", "Sudbury VT"), ("sunderland", "vt", "Sunderland VT"),
    ("sutton", "vt", "Sutton VT"), ("swanton", "vt", "Swanton VT"),
    ("thetford", "vt", "Thetford VT"), ("tinmouth", "vt", "Tinmouth VT"),
    ("topsham", "vt", "Topsham VT"), ("townshend", "vt", "Townshend VT"),
    ("troy", "vt", "Troy VT"), ("tunbridge", "vt", "Tunbridge VT"),
    ("underhill", "vt", "Underhill VT"), ("vergennes", "vt", "Vergennes VT"),
    ("vernon", "vt", "Vernon VT"), ("vershire", "vt", "Vershire VT"),
    ("victory", "vt", "Victory VT"), ("waitsfield", "vt", "Waitsfield VT"),
    ("walcott", "vt", "Walcott VT"), ("walden", "vt", "Walden VT"),
    ("wallingford", "vt", "Wallingford VT"), ("wardsboro", "vt", "Wardsboro VT"),
    ("warren", "vt", "Warren VT"), ("washington", "vt", "Washington VT"),
    ("waterbury", "vt", "Waterbury VT"), ("waterford", "vt", "Waterford VT"),
    ("waterville", "vt", "Waterville VT"), ("weathersfield", "vt", "Weathersfield VT"),
    ("wells", "vt", "Wells VT"), ("west fairlee", "vt", "West Fairlee VT"),
    ("west haven", "vt", "West Haven VT"), ("west rutland", "vt", "West Rutland VT"),
    ("west windsor", "vt", "West Windsor VT"), ("westfield", "vt", "Westfield VT"),
    ("westford", "vt", "Westford VT"), ("westminster", "vt", "Westminster VT"),
    ("westmore", "vt", "Westmore VT"), ("weston", "vt", "Weston VT"),
    ("whiting", "vt", "Whiting VT"), ("whitingham", "vt", "Whitingham VT"),
    ("williamstown", "vt", "Williamstown VT"), ("williston", "vt", "Williston VT"),
    ("wilmington", "vt", "Wilmington VT"), ("windham", "vt", "Windham VT"),
    ("windsor", "vt", "Windsor VT"), ("winhall", "vt", "Winhall VT"),
    ("winooski", "vt", "Winooski VT"), ("wolcott", "vt", "Wolcott VT"),
    ("woodbury", "vt", "Woodbury VT"), ("woodford", "vt", "Woodford VT"),
    ("woodstock", "vt", "Woodstock VT"), ("worcester", "vt", "Worcester VT"),

    # Maine — more towns
    ("auburn", "me", "Auburn ME"), ("augusta", "me", "Augusta ME"),
    ("bangor", "me", "Bangor ME"), ("bath", "me", "Bath ME"),
    ("belfast", "me", "Belfast ME"), ("berwick", "me", "Berwick ME"),
    ("biddeford", "me", "Biddeford ME"), ("brewer", "me", "Brewer ME"),
    ("bridgton", "me", "Bridgton ME"), ("brunswick", "me", "Brunswick ME"),
    ("buxton", "me", "Buxton ME"), ("calais", "me", "Calais ME"),
    ("camden", "me", "Camden ME"), ("cape elizabeth", "me", "Cape Elizabeth ME"),
    ("capeelizabeth", "me", "Cape Elizabeth ME"),
    ("caribou", "me", "Caribou ME"), ("cumberland", "me", "Cumberland ME"),
    ("east millinocket", "me", "East Millinocket ME"),
    ("ellsworth", "me", "Ellsworth ME"), ("eliot", "me", "Eliot ME"),
    ("falmouth", "me", "Falmouth ME"), ("farmington", "me", "Farmington ME"),
    ("freeport", "me", "Freeport ME"), ("frenchville", "me", "Frenchville ME"),
    ("gardiner", "me", "Gardiner ME"), ("gorham", "me", "Gorham ME"),
    ("gray", "me", "Gray ME"), ("houlton", "me", "Houlton ME"),
    ("kennebunk", "me", "Kennebunk ME"), ("kennebunkport", "me", "Kennebunkport ME"),
    ("kittery", "me", "Kittery ME"), ("lewiston", "me", "Lewiston ME"),
    ("lincoln", "me", "Lincoln ME"), ("lisbon", "me", "Lisbon ME"),
    ("lyman", "me", "Lyman ME"), ("millinocket", "me", "Millinocket ME"),
    ("naples", "me", "Naples ME"), ("north berwick", "me", "North Berwick ME"),
    ("northberwick", "me", "North Berwick ME"), ("norway", "me", "Norway ME"),
    ("old orchard beach", "me", "Old Orchard Beach ME"),
    ("oldorchardbeach", "me", "Old Orchard Beach ME"),
    ("old town", "me", "Old Town ME"), ("oldtown", "me", "Old Town ME"),
    ("orono", "me", "Orono ME"), ("oxford", "me", "Oxford ME"),
    ("paris", "me", "Paris ME"), ("pittsfield", "me", "Pittsfield ME"),
    ("portland", "me", "Portland ME"), ("presque isle", "me", "Presque Isle ME"),
    ("presqueisle", "me", "Presque Isle ME"), ("raymond", "me", "Raymond ME"),
    ("rockland", "me", "Rockland ME"), ("rockport", "me", "Rockport ME"),
    ("rumford", "me", "Rumford ME"), ("saco", "me", "Saco ME"),
    ("sanford", "me", "Sanford ME"), ("scarborough", "me", "Scarborough ME"),
    ("skowhegan", "me", "Skowhegan ME"), ("south berwick", "me", "South Berwick ME"),
    ("southberwick", "me", "South Berwick ME"),
    ("south portland", "me", "South Portland ME"),
    ("southportland", "me", "South Portland ME"),
    ("standish", "me", "Standish ME"), ("topsham", "me", "Topsham ME"),
    ("waterboro", "me", "Waterboro ME"), ("waterville", "me", "Waterville ME"),
    ("wells", "me", "Wells ME"), ("westbrook", "me", "Westbrook ME"),
    ("windham", "me", "Windham ME"), ("winslow", "me", "Winslow ME"),
    ("winterport", "me", "Winterport ME"), ("winthrop", "me", "Winthrop ME"),
    ("yarmouth", "me", "Yarmouth ME"), ("york", "me", "York ME"),
    ("yarmouthme", "me", "Yarmouth ME"), ("ogunquit", "me", "Ogunquit ME"),

    # More TX cities
    ("amarillotx", "tx", "Amarillo TX"), ("abilenetx", "tx", "Abilene TX"),
    ("arlingtontx", "tx", "Arlington TX"), ("austintx", "tx", "Austin TX"),
    ("baytowntx", "tx", "Baytown TX"), ("beaumonttx", "tx", "Beaumont TX"),
    ("brownsvilletx", "tx", "Brownsville TX"), ("carrolltontx", "tx", "Carrollton TX"),
    ("cedarparkx", "tx", "Cedar Park TX"), ("cedarparktx", "tx", "Cedar Park TX"),
    ("collegestationtx", "tx", "College Station TX"),
    ("corpus christitx", "tx", "Corpus Christi TX"),
    ("corsicanatx", "tx", "Corsicana TX"), ("dallasd", "tx", "Dallas TX"),
    ("dentontx", "tx", "Denton TX"), ("edinburgtx", "tx", "Edinburg TX"),
    ("edintx", "tx", "Edinburg TX"), ("elp", "tx", "El Paso TX"),
    ("eualesstx", "tx", "Euless TX"), ("eulestx", "tx", "Euless TX"),
    ("flowermoundtx", "tx", "Flower Mound TX"),
    ("fortworthtx", "tx", "Fort Worth TX"), ("friscotx", "tx", "Frisco TX"),
    ("garlandtx", "tx", "Garland TX"), ("grandprairietx", "tx", "Grand Prairie TX"),
    ("grapevinetx", "tx", "Grapevine TX"), ("harlingentx", "tx", "Harlingen TX"),
    ("houstontx", "tx", "Houston TX"), ("irvingtx", "tx", "Irving TX"),
    ("killeentx", "tx", "Killeen TX"), ("kylexy", "tx", "Kyle TX"),
    ("kyletx", "tx", "Kyle TX"), ("laredo tx", "tx", "Laredo TX"),
    ("lareditx", "tx", "Laredo TX"), ("laredotx", "tx", "Laredo TX"),
    ("leaguecitytx", "tx", "League City TX"), ("lewisvilletx", "tx", "Lewisville TX"),
    ("longviewtx", "tx", "Longview TX"), ("lubborktx", "tx", "Lubbock TX"),
    ("lubocktx", "tx", "Lubbock TX"), ("lubbocktx", "tx", "Lubbock TX"),
    ("mCallentx", "tx", "McAllen TX"), ("mcallentx", "tx", "McAllen TX"),
    ("mckinneytx", "tx", "McKinney TX"), ("mesquitetx", "tx", "Mesquite TX"),
    ("midlandtx", "tx", "Midland TX"), ("odessatx", "tx", "Odessa TX"),
    ("pasadenatx", "tx", "Pasadena TX"), ("pearlandtx", "tx", "Pearland TX"),
    ("pflugervilletx", "tx", "Pflugerville TX"), ("planotx", "tx", "Plano TX"),
    ("richardson tx", "tx", "Richardson TX"), ("richardsontx", "tx", "Richardson TX"),
    ("round rocktx", "tx", "Round Rock TX"), ("roundrocktx", "tx", "Round Rock TX"),
    ("sanantioniotx", "tx", "San Antonio TX"), ("sanantioniotx", "tx", "San Antonio TX"),
    ("sanantoniiotx", "tx", "San Antonio TX"), ("sanantoniox", "tx", "San Antonio TX"),
    ("sanantotx", "tx", "San Antonio TX"), ("sanantonio", "tx", "San Antonio TX"),
    ("sugarlandtx", "tx", "Sugar Land TX"), ("templetx", "tx", "Temple TX"),
    ("tylertx", "tx", "Tyler TX"), ("wacotx", "tx", "Waco TX"),
    ("wichitafallstx", "tx", "Wichita Falls TX"),

    # More CO cities
    ("arvaadaco", "co", "Arvada CO"), ("arvadaco", "co", "Arvada CO"),
    ("auroracounty", "co", "Aurora CO"), ("auroracol", "co", "Aurora CO"),
    ("auroraco", "co", "Aurora CO"), ("boulderco", "co", "Boulder CO"),
    ("brightonco", "co", "Brighton CO"), ("broomfieldco", "co", "Broomfield CO"),
    ("castlerockco", "co", "Castle Rock CO"), ("centennialco", "co", "Centennial CO"),
    ("coloradospringsco", "co", "Colorado Springs CO"),
    ("commercecityco", "co", "Commerce City CO"), ("englwoodco", "co", "Englewood CO"),
    ("fortcollinsco", "co", "Fort Collins CO"), ("greeleyco", "co", "Greeley CO"),
    ("highlandsranchco", "co", "Highlands Ranch CO"),
    ("lakewoodco", "co", "Lakewood CO"), ("longmontco", "co", "Longmont CO"),
    ("lovelandcountyco", "co", "Loveland CO"), ("parkertco", "co", "Parker CO"),
    ("parkerco", "co", "Parker CO"), ("pueblocoiyt", "co", "Pueblo CO"),
    ("thorntonco", "co", "Thornton CO"), ("westminsterco", "co", "Westminster CO"),
    ("wheatridgecounty", "co", "Wheat Ridge CO"),

    # More FL
    ("bocaratonfl", "fl", "Boca Raton FL"), ("bonitaspringsfl", "fl", "Bonita Springs FL"),
    ("bradentonfl", "fl", "Bradenton FL"), ("capecoralfl", "fl", "Cape Coral FL"),
    ("clearwaterfl", "fl", "Clearwater FL"), ("coralspringsfl", "fl", "Coral Springs FL"),
    ("deltona fl", "fl", "Deltona FL"), ("deltonafl", "fl", "Deltona FL"),
    ("fortlauderdalefl", "fl", "Fort Lauderdale FL"), ("gainesvillefl", "fl", "Gainesville FL"),
    ("hollywoodfl", "fl", "Hollywood FL"), ("homesteadfl", "fl", "Homestead FL"),
    ("jacksonvillefl", "fl", "Jacksonville FL"), ("jupiterfl", "fl", "Jupiter FL"),
    ("kissimmeefl", "fl", "Kissimmee FL"), ("lakelandfl", "fl", "Lakeland FL"),
    ("largofl", "fl", "Largo FL"), ("melbournefl", "fl", "Melbourne FL"),
    ("miramarfl", "fl", "Miramar FL"), ("naplesfl", "fl", "Naples FL"),
    ("ocalafl", "fl", "Ocala FL"), ("orlandofl", "fl", "Orlando FL"),
    ("palmbayfl", "fl", "Palm Bay FL"), ("pensacolafl", "fl", "Pensacola FL"),
    ("pompanobeachfl", "fl", "Pompano Beach FL"),
    ("portstluciefl", "fl", "Port St. Lucie FL"), ("sarasotafl", "fl", "Sarasota FL"),
    ("tallahasseell", "fl", "Tallahassee FL"), ("tallahasseefl", "fl", "Tallahassee FL"),
    ("westpalmbeachfl", "fl", "West Palm Beach FL"),

    # More GA
    ("alpharettaga", "ga", "Alpharetta GA"), ("athensga", "ga", "Athens GA"),
    ("atlantaga", "ga", "Atlanta GA"), ("augustaga", "ga", "Augusta GA"),
    ("brookhavengA", "ga", "Brookhaven GA"), ("brookhavenga", "ga", "Brookhaven GA"),
    ("cantonGA", "ga", "Canton GA"), ("cantonga", "ga", "Canton GA"),
    ("cartersvillega", "ga", "Cartersville GA"), ("chambleega", "ga", "Chamblee GA"),
    ("columbusga", "ga", "Columbus GA"), ("covingtonga", "ga", "Covington GA"),
    ("duluthga", "ga", "Duluth GA"), ("dunwoodyga", "ga", "Dunwoody GA"),
    ("gainesvillega", "ga", "Gainesville GA"), ("johnscreekga", "ga", "Johns Creek GA"),
    ("kennewsawga", "ga", "Kennesaw GA"), ("kennesawga", "ga", "Kennesaw GA"),
    ("lawrencevillega", "ga", "Lawrenceville GA"), ("maconga", "ga", "Macon GA"),
    ("mariettaga", "ga", "Marietta GA"), ("mcdonoughga", "ga", "McDonough GA"),
    ("miltonga", "ga", "Milton GA"), ("peachtreecityga", "ga", "Peachtree City GA"),
    ("romega", "ga", "Rome GA"), ("roswellga", "ga", "Roswell GA"),
    ("savannahga", "ga", "Savannah GA"), ("smyrnaga", "ga", "Smyrna GA"),
    ("stockbridgega", "ga", "Stockbridge GA"), ("tuckergA", "ga", "Tucker GA"),
    ("tuckerga", "ga", "Tucker GA"), ("valdostaga", "ga", "Valdosta GA"),
    ("warnerrobinsga", "ga", "Warner Robins GA"), ("woodstockga", "ga", "Woodstock GA"),
    ("dekalbcountyga", "ga", "DeKalb County GA"),
    ("fultoncountyga", "ga", "Fulton County GA"),
    ("gwinnettcountyga", "ga", "Gwinnett County GA"),
    ("cobbcountyga", "ga", "Cobb County GA"),
    ("henrycountyga", "ga", "Henry County GA"),
    ("cherokee county", "ga", "Cherokee County GA"),
    ("cherokeecounty", "ga", "Cherokee County GA"),
    ("forsythcountyga", "ga", "Forsyth County GA"),
    ("claytonounty", "ga", "Clayton County GA"),
    ("claytoncounty", "ga", "Clayton County GA"),

    # More WA
    ("auburnwa", "wa", "Auburn WA"), ("bellevuewa", "wa", "Bellevue WA"),
    ("bellinghamwa", "wa", "Bellingham WA"), ("bothellwa", "wa", "Bothell WA"),
    ("burienwa", "wa", "Burien WA"), ("edmonds wa", "wa", "Edmonds WA"),
    ("edmondswa", "wa", "Edmonds WA"), ("everettwa", "wa", "Everett WA"),
    ("federalwaywa", "wa", "Federal Way WA"), ("kentwa", "wa", "Kent WA"),
    ("kennewickwa", "wa", "Kennewick WA"), ("kirklandwa", "wa", "Kirkland WA"),
    ("lakeywoodwa", "wa", "Lakewood WA"), ("lakewoodwa", "wa", "Lakewood WA"),
    ("lynnwoodwa", "wa", "Lynnwood WA"), ("marysvillewa", "wa", "Marysville WA"),
    ("olympiawa", "wa", "Olympia WA"), ("pascowa", "wa", "Pasco WA"),
    ("puyallupwa", "wa", "Puyallup WA"), ("redmondwa", "wa", "Redmond WA"),
    ("rentonwa", "wa", "Renton WA"), ("richlandwa", "wa", "Richland WA"),
    ("sammamishwa", "wa", "Sammamish WA"), ("seattlewa", "wa", "Seattle WA"),
    ("shorelinewa", "wa", "Shoreline WA"), ("spokanewa", "wa", "Spokane WA"),
    ("spokanevalleywa", "wa", "Spokane Valley WA"),
    ("tacomawa", "wa", "Tacoma WA"), ("tukwilawa", "wa", "Tukwila WA"),
    ("vancouverwa", "wa", "Vancouver WA"), ("wallawallawa", "wa", "Walla Walla WA"),
    ("wenatcheewa", "wa", "Wenatchee WA"), ("yakimawa", "wa", "Yakima WA"),

    # More NC
    ("ashevilenc", "nc", "Asheville NC"), ("burlingtonnc", "nc", "Burlington NC"),
    ("carync", "nc", "Cary NC"), ("charlottenc", "nc", "Charlotte NC"),
    ("concordnc", "nc", "Concord NC"), ("durhamnc", "nc", "Durham NC"),
    ("fayettevillenc", "nc", "Fayetteville NC"), ("gastoniannc", "nc", "Gastonia NC"),
    ("gastonia nc", "nc", "Gastonia NC"), ("gastoniAnc", "nc", "Gastonia NC"),
    ("gastoniank", "nc", "Gastonia NC"), ("gastolianc", "nc", "Gastonia NC"),
    ("gastolianc", "nc", "Gastonia NC"), ("gastolianc", "nc", "Gastonia NC"),
    ("greensboronc", "nc", "Greensboro NC"), ("greenvilknc", "nc", "Greenville NC"),
    ("greenvillenc", "nc", "Greenville NC"), ("hickorync", "nc", "Hickory NC"),
    ("highpointnc", "nc", "High Point NC"), ("huntersvillenc", "nc", "Huntersville NC"),
    ("jacksonvillenc", "nc", "Jacksonville NC"), ("kannapolisnc", "nc", "Kannapolis NC"),
    ("morrisvillenc", "nc", "Morrisville NC"), ("raleighnc", "nc", "Raleigh NC"),
    ("rockymountnc", "nc", "Rocky Mount NC"), ("wakeforest nc", "nc", "Wake Forest NC"),
    ("wakeforestvc", "nc", "Wake Forest NC"), ("wakeforrestnc", "nc", "Wake Forest NC"),
    ("wilmingtonnc", "nc", "Wilmington NC"), ("wilsonnc", "nc", "Wilson NC"),
    ("winstonsalemnc", "nc", "Winston-Salem NC"),

    # More OH
    ("akronoh", "oh", "Akron OH"), ("cantonoh", "oh", "Canton OH"),
    ("cincinnatioh", "oh", "Cincinnati OH"), ("clevelandoh", "oh", "Cleveland OH"),
    ("columbusoh", "oh", "Columbus OH"), ("daytonoh", "oh", "Dayton OH"),
    ("eulidoh", "oh", "Euclid OH"), ("euclidoh", "oh", "Euclid OH"),
    ("grovecityoh", "oh", "Grove City OH"), ("hamiltonoh", "oh", "Hamilton OH"),
    ("ketteringoh", "oh", "Kettering OH"), ("lakewoodoh", "oh", "Lakewood OH"),
    ("lancasteroh", "oh", "Lancaster OH"), ("mansfieldoh", "oh", "Mansfield OH"),
    ("masonoh", "oh", "Mason OH"), ("mentooh", "oh", "Mentor OH"),
    ("mentoroh", "oh", "Mentor OH"), ("newarkoh", "oh", "Newark OH"),
    ("paRmaoh", "oh", "Parma OH"), ("parmaoh", "oh", "Parma OH"),
    ("sanduskyoh", "oh", "Sandusky OH"), ("springfieldoh", "oh", "Springfield OH"),
    ("stowoh", "oh", "Stow OH"), ("strongsvilleoh", "oh", "Strongsville OH"),
    ("toledooh", "oh", "Toledo OH"), ("westervilleoh", "oh", "Westerville OH"),
    ("youngstownoh", "oh", "Youngstown OH"),

    # More WI
    ("appletonwi", "wi", "Appleton WI"), ("eau clairewi", "wi", "Eau Claire WI"),
    ("eauclairewi", "wi", "Eau Claire WI"), ("fond du lacwi", "wi", "Fond du Lac WI"),
    ("fonddulaicwi", "wi", "Fond du Lac WI"), ("fonddulatwi", "wi", "Fond du Lac WI"),
    ("greenbWaywi", "wi", "Green Bay WI"), ("greenbaywi", "wi", "Green Bay WI"),
    ("janesvillwi", "wi", "Janesville WI"), ("janesvillewi", "wi", "Janesville WI"),
    ("kenoshawi", "wi", "Kenosha WI"), ("madisonwi", "wi", "Madison WI"),
    ("manitowocwi", "wi", "Manitowoc WI"), ("milwaukeewi", "wi", "Milwaukee WI"),
    ("oshkoshwi", "wi", "Oshkosh WI"), ("racinewi", "wi", "Racine WI"),
    ("sheboyganwi", "wi", "Sheboygan WI"), ("superiorwi", "wi", "Superior WI"),
    ("waukeshawi", "wi", "Waukesha WI"), ("wausauwi", "wi", "Wausau WI"),
    ("westalliswi", "wi", "West Allis WI"),

    # More MN
    ("applevalleymn", "mn", "Apple Valley MN"),
    ("bloomingtonmn", "mn", "Bloomington MN"),
    ("brooklynparkmn", "mn", "Brooklyn Park MN"),
    ("burnsvillemn", "mn", "Burnsville MN"),
    ("coonrapidsmn", "mn", "Coon Rapids MN"),
    ("dulthumN", "mn", "Duluth MN"), ("dulthmn", "mn", "Duluth MN"),
    ("dulthmn2", "mn", "Duluth MN"), ("duluthmn", "mn", "Duluth MN"),
    ("eaganmn", "mn", "Eagan MN"), ("edenprariemn", "mn", "Eden Prairie MN"),
    ("edinamn", "mn", "Edina MN"), ("lakevillemn", "mn", "Lakeville MN"),
    ("mankatomn", "mn", "Mankato MN"), ("maplgrovemn", "mn", "Maple Grove MN"),
    ("maplegrovemn", "mn", "Maple Grove MN"),
    ("minneapolismn", "mn", "Minneapolis MN"), ("minnetonkamn", "mn", "Minnetonka MN"),
    ("moorheadmn", "mn", "Moorhead MN"), ("plymouthmn", "mn", "Plymouth MN"),
    ("richfieldmn", "mn", "Richfield MN"), ("rochestermn", "mn", "Rochester MN"),
    ("rosevillemn", "mn", "Roseville MN"), ("saintcloudmn", "mn", "Saint Cloud MN"),
    ("saintpaulmn", "mn", "Saint Paul MN"), ("woodburymn", "mn", "Woodbury MN"),

    # More IL
    ("auroRail", "il", "Aurora IL"), ("aurorail", "il", "Aurora IL"),
    ("bloomingtonil", "il", "Bloomington IL"),
    ("chicagil", "il", "Chicago IL"), ("chicagoil", "il", "Chicago IL"),
    ("ciceroil", "il", "Cicero IL"), ("crystallakeil", "il", "Crystal Lake IL"),
    ("elginil", "il", "Elgin IL"), ("evanstonil", "il", "Evanston IL"),
    ("joilietil", "il", "Joliet IL"), ("joliettil", "il", "Joliet IL"),
    ("jolietil", "il", "Joliet IL"), ("napervillleil", "il", "Naperville IL"),
    ("napervilleil", "il", "Naperville IL"), ("normalil", "il", "Normal IL"),
    ("orlandparkil", "il", "Orland Park IL"), ("palatineil", "il", "Palatine IL"),
    ("peoriail", "il", "Peoria IL"), ("rockfordil", "il", "Rockford IL"),
    ("schaumburgil", "il", "Schaumburg IL"), ("springfieldil", "il", "Springfield IL"),
    ("tinleyparkil", "il", "Tinley Park IL"), ("waukeganil", "il", "Waukegan IL"),
    ("wheatonil", "il", "Wheaton IL"),

    # More IN
    ("andersonin", "in", "Anderson IN"), ("bloomingtoniIn", "in", "Bloomington IN"),
    ("bloomingtonin", "in", "Bloomington IN"), ("carmelin", "in", "Carmel IN"),
    ("columbusin", "in", "Columbus IN"), ("evansvillein", "in", "Evansville IN"),
    ("fishersin", "in", "Fishers IN"), ("fortwaynein", "in", "Fort Wayne IN"),
    ("garyin", "in", "Gary IN"), ("greenwoodin", "in", "Greenwood IN"),
    ("hammondin", "in", "Hammond IN"), ("indianapolisin", "in", "Indianapolis IN"),
    ("kokomoin", "in", "Kokomo IN"), ("lafayettein", "in", "Lafayette IN"),
    ("merrillvillein", "in", "Merrillville IN"), ("mishawakain", "in", "Mishawaka IN"),
    ("munciein", "in", "Muncie IN"), ("nobleSvillein", "in", "Noblesville IN"),
    ("nobleSvilein", "in", "Noblesville IN"), ("noblesvillein", "in", "Noblesville IN"),
    ("southbendin", "in", "South Bend IN"), ("terrhauttein", "in", "Terre Haute IN"),
    ("terrehautein", "in", "Terre Haute IN"), ("westfieldin", "in", "Westfield IN"),
    ("zionvillein", "in", "Zionsville IN"),

    # More TN
    ("bartletttn", "tn", "Bartlett TN"), ("brentwoodtn", "tn", "Brentwood TN"),
    ("chattanoogaaTn", "tn", "Chattanooga TN"), ("chattanooatn", "tn", "Chattanooga TN"),
    ("chattanoogatin", "tn", "Chattanooga TN"), ("chattanoogatn", "tn", "Chattanooga TN"),
    ("clarksvilletn", "tn", "Clarksville TN"), ("collieTvilletn", "tn", "Collierville TN"),
    ("colliervilletn", "tn", "Collierville TN"), ("columbiatn", "tn", "Columbia TN"),
    ("franklintn", "tn", "Franklin TN"), ("germantowntn", "tn", "Germantown TN"),
    ("hendersolnvilletn", "tn", "Hendersonville TN"),
    ("hendersonville tn", "tn", "Hendersonville TN"),
    ("hendersonvilletn", "tn", "Hendersonville TN"),
    ("jacksonms", "tn", "Jackson TN"), ("kingsporttn", "tn", "Kingsport TN"),
    ("knoxvilletn", "tn", "Knoxville TN"), ("memphistn", "tn", "Memphis TN"),
    ("morristowntn", "tn", "Morristown TN"), ("murfreesborotn", "tn", "Murfreesboro TN"),
    ("nashvilletn", "tn", "Nashville TN"), ("smyrnatn", "tn", "Smyrna TN"),
    ("springhilltn", "tn", "Spring Hill TN"),

    # More PA
    ("allentownpa", "pa", "Allentown PA"), ("altoonapa", "pa", "Altoona PA"),
    ("bethlehempa", "pa", "Bethlehem PA"), ("eriepa", "pa", "Erie PA"),
    ("harrisburgpa", "pa", "Harrisburg PA"), ("lancasterpa", "pa", "Lancaster PA"),
    ("philadelphiapa", "pa", "Philadelphia PA"), ("pittsburghpa", "pa", "Pittsburgh PA"),
    ("readingpa", "pa", "Reading PA"), ("scrantonpa", "pa", "Scranton PA"),
    ("yorkpa", "pa", "York PA"),

    # More VA
    ("alexandriava", "va", "Alexandria VA"), ("arlingtonva", "va", "Arlington VA"),
    ("charlottesvilleva", "va", "Charlottesville VA"),
    ("chesapeakeva", "va", "Chesapeake VA"), ("fredericksburgva", "va", "Fredericksburg VA"),
    ("hamptonva", "va", "Hampton VA"), ("harrisonburgva", "va", "Harrisonburg VA"),
    ("lynchburgva", "va", "Lynchburg VA"), ("manassasva", "va", "Manassas VA"),
    ("newportnewsva", "va", "Newport News VA"), ("norfolkva", "va", "Norfolk VA"),
    ("portsmouthva", "va", "Portsmouth VA"), ("richmondva", "va", "Richmond VA"),
    ("roanokeva", "va", "Roanoke VA"), ("suffolkva", "va", "Suffolk VA"),
    ("virginiabeachva", "va", "Virginia Beach VA"),

    # More OR
    ("albanyory", "or", "Albany OR"), ("albonyor", "or", "Albany OR"),
    ("albanyor", "or", "Albany OR"), ("beavertonor", "or", "Beaverton OR"),
    ("bendor", "or", "Bend OR"), ("corvallisOr", "or", "Corvallis OR"),
    ("corvallisor", "or", "Corvallis OR"), ("eugeneor", "or", "Eugene OR"),
    ("greshamor", "or", "Gresham OR"), ("hillsboroOr", "or", "Hillsboro OR"),
    ("hillsboroor", "or", "Hillsboro OR"), ("lakeoswegor", "or", "Lake Oswego OR"),
    ("medfordor", "or", "Medford OR"), ("portlandor", "or", "Portland OR"),
    ("salendor", "or", "Salem OR"), ("salemor", "or", "Salem OR"),
    ("springfieldor", "or", "Springfield OR"), ("tigardor", "or", "Tigard OR"),

    # More AZ
    ("avondaleaz", "az", "Avondale AZ"), ("buckeyeaz", "az", "Buckeye AZ"),
    ("chandleraz", "az", "Chandler AZ"), ("flagstaffaz", "az", "Flagstaff AZ"),
    ("gilbertaz", "az", "Gilbert AZ"), ("glendaleaz", "az", "Glendale AZ"),
    ("goodyearaz", "az", "Goodyear AZ"), ("lakehavasucityaz", "az", "Lake Havasu City AZ"),
    ("maricopaaz", "az", "Maricopa AZ"), ("mesaaz", "az", "Mesa AZ"),
    ("peoriaaz", "az", "Peoria AZ"), ("prescottaz", "az", "Prescott AZ"),
    ("queencreekaz", "az", "Queen Creek AZ"), ("scottsdaleaz", "az", "Scottsdale AZ"),
    ("surpriseaz", "az", "Surprise AZ"), ("tempeaz", "az", "Tempe AZ"),
    ("tucsonaz", "az", "Tucson AZ"),

    # More NJ
    ("baynonne", "nj", "Bayonne NJ"), ("bayonnenj", "nj", "Bayonne NJ"),
    ("camdennj", "nj", "Camden NJ"), ("cherryHillnj", "nj", "Cherry Hill NJ"),
    ("cherryhillnj", "nj", "Cherry Hill NJ"), ("cliftonnj", "nj", "Clifton NJ"),
    ("edisonNj", "nj", "Edison NJ"), ("edisonnj", "nj", "Edison NJ"),
    ("elizabethnj", "nj", "Elizabeth NJ"), ("hackensacknj", "nj", "Hackensack NJ"),
    ("jerseycitynj", "nj", "Jersey City NJ"), ("lakewoodnj", "nj", "Lakewood NJ"),
    ("newanrknj", "nj", "Newark NJ"), ("newarknj", "nj", "Newark NJ"),
    ("newbrunswicnj", "nj", "New Brunswick NJ"), ("newbrunwicknj", "nj", "New Brunswick NJ"),
    ("newbrunswicknj", "nj", "New Brunswick NJ"),
    ("parsipppanynj", "nj", "Parsippany NJ"), ("parsippanynj", "nj", "Parsippany NJ"),
    ("passaicnj", "nj", "Passaic NJ"), ("patersnj", "nj", "Paterson NJ"),
    ("pateronnj", "nj", "Paterson NJ"), ("patersonnj", "nj", "Paterson NJ"),
    ("piscatawynj", "nj", "Piscataway NJ"), ("piscatawaynj", "nj", "Piscataway NJ"),
    ("plainfieldnj", "nj", "Plainfield NJ"), ("toms Rivernj", "nj", "Toms River NJ"),
    ("tomsrivernj", "nj", "Toms River NJ"), ("trentonNj", "nj", "Trenton NJ"),
    ("trentonnj", "nj", "Trenton NJ"), ("unionncitynj", "nj", "Union City NJ"),
    ("unioncitynj", "nj", "Union City NJ"),

    # More MI
    ("annarbor mi", "mi", "Ann Arbor MI"), ("annarbornmi", "mi", "Ann Arbor MI"),
    ("annarbomi", "mi", "Ann Arbor MI"), ("annarbormi", "mi", "Ann Arbor MI"),
    ("battlecreekmi", "mi", "Battle Creek MI"), ("dearbornmi", "mi", "Dearborn MI"),
    ("detroitmi", "mi", "Detroit MI"), ("eastlansingmi", "mi", "East Lansing MI"),
    ("flintmi", "mi", "Flint MI"), ("grandrapidsmi", "mi", "Grand Rapids MI"),
    ("kalamazooMi", "mi", "Kalamazoo MI"), ("kalamazoo mi", "mi", "Kalamazoo MI"),
    ("kalamazoomi", "mi", "Kalamazoo MI"), ("lansingmi", "mi", "Lansing MI"),
    ("livoniami", "mi", "Livonia MI"), ("muncie mi", "mi", "Muskegon MI"),
    ("muskegonmi", "mi", "Muskegon MI"), ("novimi", "mi", "Novi MI"),
    ("royaloakmi", "mi", "Royal Oak MI"), ("southfieldmi", "mi", "Southfield MI"),
    ("sterling heights mi", "mi", "Sterling Heights MI"),
    ("sterlingheightsmi", "mi", "Sterling Heights MI"),
    ("taylormi", "mi", "Taylor MI"), ("troymi", "mi", "Troy MI"),
    ("warrenmI", "mi", "Warren MI"), ("warrenmi", "mi", "Warren MI"),
    ("westlandmi", "mi", "Westland MI"),

    # More KS
    ("hutchinsonks", "ks", "Hutchinson KS"), ("kansascityks", "ks", "Kansas City KS"),
    ("lawrenceks", "ks", "Lawrence KS"), ("lenexaks", "ks", "Lenexa KS"),
    ("manhatanks", "ks", "Manhattan KS"), ("manhattanks", "ks", "Manhattan KS"),
    ("olatheks", "ks", "Olathe KS"), ("overlandparkks", "ks", "Overland Park KS"),
    ("salinaks", "ks", "Salina KS"), ("shawneeks", "ks", "Shawnee KS"),
    ("topekaks", "ks", "Topeka KS"), ("wichitaks", "ks", "Wichita KS"),
    ("goddardks", "ks", "Goddard KS"), ("springhillks", "ks", "Spring Hill KS"),

    # More KY
    ("bowlinggreennky", "ky", "Bowling Green KY"), ("bowlingreenky", "ky", "Bowling Green KY"),
    ("bowlinggreennky", "ky", "Bowling Green KY"),
    ("lexingtonky", "ky", "Lexington KY"), ("louisvillky", "ky", "Louisville KY"),
    ("louisvilleky", "ky", "Louisville KY"), ("owensboroky", "ky", "Owensboro KY"),
    ("paducahky", "ky", "Paducah KY"), ("richmonky", "ky", "Richmond KY"),
    ("richmondky", "ky", "Richmond KY"),

    # More SC
    ("charlestonsc", "sc", "Charleston SC"), ("columbiasc", "sc", "Columbia SC"),
    ("florencesc", "sc", "Florence SC"), ("greenvillesc", "sc", "Greenville SC"),
    ("greenviillesc", "sc", "Greenville SC"), ("greenwoodsc", "sc", "Greenwood SC"),
    ("hiltonheadsc", "sc", "Hilton Head SC"), ("myrtlebeachsc", "sc", "Myrtle Beach SC"),
    ("northcharlestonsc", "sc", "North Charleston SC"),
    ("rockhillsc", "sc", "Rock Hill SC"), ("spartanburgsc", "sc", "Spartanburg SC"),
    ("summervillesc", "sc", "Summerville SC"), ("sumtersc", "sc", "Sumter SC"),

    # More NV
    ("carsoncitynv", "nv", "Carson City NV"), ("hendersonnv", "nv", "Henderson NV"),
    ("lasvegasnv", "nv", "Las Vegas NV"), ("northlasvegas nv", "nv", "North Las Vegas NV"),
    ("northlasvegasnv", "nv", "North Las Vegas NV"), ("renonv", "nv", "Reno NV"),
    ("sparksnv", "nv", "Sparks NV"),

    # More NM
    ("albuquerquenm", "nm", "Albuquerque NM"), ("clovisnm", "nm", "Clovis NM"),
    ("farmingtonnnm", "nm", "Farmington NM"), ("farmingtonnm", "nm", "Farmington NM"),
    ("hobbsnm", "nm", "Hobbs NM"), ("lasCruces nm", "nm", "Las Cruces NM"),
    ("lascrucesnm", "nm", "Las Cruces NM"), ("rioRanchorn", "nm", "Rio Rancho NM"),
    ("rioranchonm", "nm", "Rio Rancho NM"), ("roswellnm", "nm", "Roswell NM"),

    # More ID
    ("boiseid", "id", "Boise ID"), ("caldwellid", "id", "Caldwell ID"),
    ("coeurdaleneid", "id", "Coeur d'Alene ID"), ("idahofallsid", "id", "Idaho Falls ID"),
    ("lewistonid", "id", "Lewiston ID"), ("meridianid", "id", "Meridian ID"),
    ("namkpaid", "id", "Nampa ID"), ("nampaid", "id", "Nampa ID"),
    ("pocatelloid", "id", "Pocatello ID"), ("rexburgid", "id", "Rexburg ID"),
    ("twinFallsid", "id", "Twin Falls ID"), ("twinfallsid", "id", "Twin Falls ID"),

    # More SD
    ("aberdeensd", "sd", "Aberdeen SD"), ("brookingssd", "sd", "Brookings SD"),
    ("rapidcitysd", "sd", "Rapid City SD"), ("siouxfallssd", "sd", "Sioux Falls SD"),
    ("watertownsd", "sd", "Watertown SD"),

    # More ND
    ("bismarcknd", "nd", "Bismarck ND"), ("fargond", "nd", "Fargo ND"),
    ("grandforks nd", "nd", "Grand Forks ND"), ("grandforkslnd", "nd", "Grand Forks ND"),
    ("grandforknd", "nd", "Grand Forks ND"), ("grandforksnd", "nd", "Grand Forks ND"),
    ("minotnd", "nd", "Minot ND"),

    # More MT
    ("billingsmt", "mt", "Billings MT"), ("bozmanmt", "mt", "Bozeman MT"),
    ("bozeanmt", "mt", "Bozeman MT"), ("bozemanmt", "mt", "Bozeman MT"),
    ("buttemt", "mt", "Butte MT"), ("greatfallsmt", "mt", "Great Falls MT"),
    ("helenaml", "mt", "Helena MT"), ("helenanat", "mt", "Helena MT"),
    ("helenamt", "mt", "Helena MT"), ("kalisepellmt", "mt", "Kalispell MT"),
    ("kalispellmt", "mt", "Kalispell MT"), ("missoulaamt", "mt", "Missoula MT"),
    ("missoulacomt", "mt", "Missoula MT"), ("missoulamt", "mt", "Missoula MT"),

    # More UT
    ("americanforkut", "ut", "American Fork UT"), ("herrimanut", "ut", "Herriman UT"),
    ("laytonut", "ut", "Layton UT"), ("lehiut", "ut", "Lehi UT"),
    ("loganut", "ut", "Logan UT"), ("midvaleut", "ut", "Midvale UT"),
    ("murrayut", "ut", "Murray UT"), ("ogdenut", "ut", "Ogden UT"),
    ("oremut", "ut", "Orem UT"), ("provout", "ut", "Provo UT"),
    ("rivertout", "ut", "Riverton UT"), ("rivertonut", "ut", "Riverton UT"),
    ("saltlakecityut", "ut", "Salt Lake City UT"), ("sandyut", "ut", "Sandy UT"),
    ("southjordanut", "ut", "South Jordan UT"), ("spanishforkut", "ut", "Spanish Fork UT"),
    ("springvilleut", "ut", "Springville UT"), ("stgeorgeut", "ut", "St. George UT"),
    ("taylorvilleut", "ut", "Taylorsville UT"), ("westjordanut", "ut", "West Jordan UT"),
    ("westvalleyut", "ut", "West Valley UT"),

    # More AK
    ("anchorageak", "ak", "Anchorage AK"), ("fairbanksak", "ak", "Fairbanks AK"),
    ("juneauck", "ak", "Juneau AK"), ("juneauak", "ak", "Juneau AK"),
    ("sitkak", "ak", "Sitka AK"), ("sitkaak", "ak", "Sitka AK"),
    ("ketchikanak", "ak", "Ketchikan AK"), ("homerakt", "ak", "Homer AK"),
    ("homerak", "ak", "Homer AK"), ("palmerak", "ak", "Palmer AK"),
    ("wasillaak", "ak", "Wasilla AK"),

    # Special / non-standard slugs patterns
    ("metronashvilletn", "tn", "Metro Nashville TN"),
    ("metro nashvilletn", "tn", "Metro Nashville TN"),
    ("metrorichmond", "va", "Metro Richmond VA"),
    ("cityofrichmond", "va", "City of Richmond VA"),
    ("cityofnorfolk", "va", "City of Norfolk VA"),
    ("cityofchesapeake", "va", "City of Chesapeake VA"),
    ("cityofvirginia beach", "va", "City of Virginia Beach VA"),
    ("cityofvirginiabeach", "va", "City of Virginia Beach VA"),
    ("westernriversidecog", "ca", "Western Riverside COG CA"),
    ("westernriversideco", "ca", "Western Riverside CO CA"),
    ("westernriverside", "ca", "Western Riverside CA"),
    ("mwh2o", "ca", "Metropolitan Water District CA"),
    ("peninsulact", "ct", "Peninsula CT"),
    ("springfielddelaware", "pa", "Springfield Delaware PA"),
    ("springfieldde", "pa", "Springfield DE PA"),
    ("springfielddelco", "pa", "Springfield DelCo PA"),
    ("metronashville", "tn", "Metro Nashville TN"),
    ("johnscreekga", "ga", "Johns Creek GA"),
    ("mountpleasantny", "ny", "Mount Pleasant NY"),
    ("mountvernonny", "ny", "Mount Vernon NY"),
    ("ithacacityny", "ny", "Ithaca City NY"),
    ("princetonnj", "nj", "Princeton NJ"),
    ("valleystreamny", "ny", "Valley Stream NY"),
    ("hempsteadny", "ny", "Hempstead NY"),
    ("northstpaulmn", "mn", "North St. Paul MN"),
    ("northstpaulm", "mn", "North St. Paul MN"),
    ("oakdalemn", "mn", "Oakdale MN"),
    ("medinamn", "mn", "Medina MN"),
    ("maplevallywaMN", "mn", "Maple Valley MN"),

    # More counties (with -county suffix pattern)
    ("countyglenncounty", "ca", "Glenn County CA"),
    ("countynapa", "ca", "Napa County CA"),
    ("napacounty", "ca", "Napa County CA"),
    ("lakecountyca", "ca", "Lake County CA"),
    ("siskiyoucounty", "ca", "Siskiyou County CA"),
    ("shastacounty", "ca", "Shasta County CA"),
    ("tularecounty", "ca", "Tulare County CA"),
    ("kingscountyca", "ca", "Kings County CA"),
    ("maderacounty", "ca", "Madera County CA"),
    ("mercedcounty", "ca", "Merced County CA"),
    ("riversidefcounty", "ca", "Riverside County CA"),
    ("riversidecounty", "ca", "Riverside County CA"),
    ("sanbernardnino", "ca", "San Bernardino County CA"),
    ("sanbernordinocounty", "ca", "San Bernardino County CA"),
    ("sanbernardinocounty", "ca", "San Bernardino County CA"),
    ("orangecountyca", "ca", "Orange County CA"),
    ("contracostacounty", "ca", "Contra Costa County CA"),
    ("alamedacounty", "ca", "Alameda County CA"),
    ("sanfranciscoCOunty", "ca", "San Francisco County CA"),
    ("sanfrancisocy", "ca", "San Francisco County CA"),
    ("sanmateocounty", "ca", "San Mateo County CA"),
    ("santaclaracounty", "ca", "Santa Clara County CA"),
    ("santacruzcounty", "ca", "Santa Cruz County CA"),
    ("montereyOounty", "ca", "Monterey County CA"),
    ("montereycounty", "ca", "Monterey County CA"),
    ("sanluisobispo", "ca", "San Luis Obispo County CA"),
    ("slocountyca", "ca", "SLO County CA"),
    ("venturacounty", "ca", "Ventura County CA"),
    ("kerncounty", "ca", "Kern County CA"),
    ("sanjoaquincounty", "ca", "San Joaquin County CA"),
    ("stanislausc", "ca", "Stanislaus County CA"),
    ("stanislauscounty", "ca", "Stanislaus County CA"),
    ("eldoradocounty", "ca", "El Dorado County CA"),
    ("amdaorcounty", "ca", "Amador County CA"),
    ("amadorcounty", "ca", "Amador County CA"),
    ("calaverascounty", "ca", "Calaveras County CA"),
    ("humboldtcounty", "ca", "Humboldt County CA"),
    ("mendocinocounty", "ca", "Mendocino County CA"),
    ("yubacounty", "ca", "Yuba County CA"),
    ("suttercountyca", "ca", "Sutter County CA"),
    ("laCounty", "ca", "LA County CA"),
    ("lacountyca", "ca", "LA County CA"),
    ("loscountyla", "ca", "Los Angeles County CA"),
    ("losangelescounty", "ca", "Los Angeles County CA"),

    # Iowa more
    ("ameseia", "ia", "Ames IA"), ("amesia", "ia", "Ames IA"),
    ("cedarfallsia", "ia", "Cedar Falls IA"), ("cedarrapidsia", "ia", "Cedar Rapids IA"),
    ("davenportia", "ia", "Davenport IA"), ("desmoinesKa", "ia", "Des Moines IA"),
    ("desmoinesia", "ia", "Des Moines IA"), ("dubuqueia", "ia", "Dubuque IA"),
    ("iowacityia", "ia", "Iowa City IA"), ("siouxcityia", "ia", "Sioux City IA"),
    ("waterlooeia", "ia", "Waterloo IA"), ("waterlooia", "ia", "Waterloo IA"),
    ("westdesmoinesia", "ia", "West Des Moines IA"),

    # Oklahoma more
    ("brokenarrowok", "ok", "Broken Arrow OK"), ("edmondok", "ok", "Edmond OK"),
    ("enidok", "ok", "Enid OK"), ("lawtonok", "ok", "Lawton OK"),
    ("midwestcityok", "ok", "Midwest City OK"), ("mooreok", "ok", "Moore OK"),
    ("muskogeok", "ok", "Muskogee OK"), ("normanok", "ok", "Norman OK"),
    ("oklahomacityok", "ok", "Oklahoma City OK"), ("owassook", "ok", "Owasso OK"),
    ("stillwaterok", "ok", "Stillwater OK"), ("tulsaok", "ok", "Tulsa OK"),
    ("yukonok", "ok", "Yukon OK"),

    # More NE
    ("bellevuene", "ne", "Bellevue NE"), ("fremontne", "ne", "Fremont NE"),
    ("grandislandne", "ne", "Grand Island NE"), ("kearneyne", "ne", "Kearney NE"),
    ("lincolnne", "ne", "Lincoln NE"), ("norfolkne", "ne", "Norfolk NE"),
    ("northplattene", "ne", "North Platte NE"), ("omahaane", "ne", "Omaha NE"),
    ("omahane", "ne", "Omaha NE"), ("papillionine", "ne", "Papillion NE"),
    ("papillione", "ne", "Papillion NE"),

    # More MO
    ("bluespringsmo", "mo", "Blue Springs MO"),
    ("capegirardeanmo", "mo", "Cape Girardeau MO"),
    ("capegirardemo", "mo", "Cape Girardeau MO"),
    ("capegirardeau mo", "mo", "Cape Girardeau MO"),
    ("capegireardeaumo", "mo", "Cape Girardeau MO"),
    ("capegiradeaumo", "mo", "Cape Girardeau MO"),
    ("capegirareadumo", "mo", "Cape Girardeau MO"),
    ("chesterfieldmo", "mo", "Chesterfield MO"), ("columbiamo", "mo", "Columbia MO"),
    ("florissantmo", "mo", "Florissant MO"), ("independencemo", "mo", "Independence MO"),
    ("jeffersoncitymo", "mo", "Jefferson City MO"), ("joplinmo", "mo", "Joplin MO"),
    ("kansascitymo", "mo", "Kansas City MO"), ("leessummitmo", "mo", "Lee's Summit MO"),
    ("ofallanmo", "mo", "O'Fallon MO"), ("ofallonmo", "mo", "O'Fallon MO"),
    ("saintcharlesmo", "mo", "Saint Charles MO"), ("saintjosephmo", "mo", "Saint Joseph MO"),
    ("saintlouisxmo", "mo", "Saint Louis MO"), ("saintlouismo", "mo", "Saint Louis MO"),
    ("springfieldmo", "mo", "Springfield MO"),
    ("stlouismo", "mo", "St. Louis MO"), ("stlouiscountymo", "mo", "St. Louis County MO"),

    # More AR
    ("conwayar", "ar", "Conway AR"), ("fayettevillear", "ar", "Fayetteville AR"),
    ("fortsmithar", "ar", "Fort Smith AR"), ("jonesboraar", "ar", "Jonesboro AR"),
    ("jonesboroar", "ar", "Jonesboro AR"), ("littlerOckar", "ar", "Little Rock AR"),
    ("littlerockar", "ar", "Little Rock AR"),
    ("northlittlerOckar", "ar", "North Little Rock AR"),
    ("northlittlerockar", "ar", "North Little Rock AR"),
    ("rogersar", "ar", "Rogers AR"), ("springdalear", "ar", "Springdale AR"),
    ("bentonvillear", "ar", "Bentonville AR"),

    # More AL
    ("auburnal", "al", "Auburn AL"), ("bessemeral", "al", "Bessemer AL"),
    ("birminghamal", "al", "Birmingham AL"), ("decatural", "al", "Decatur AL"),
    ("dothanalal", "al", "Dothan AL"), ("dothanal", "al", "Dothan AL"),
    ("entrepriseal", "al", "Enterprise AL"), ("enterpriseal", "al", "Enterprise AL"),
    ("florenceal", "al", "Florence AL"), ("gadsdeal", "al", "Gadsden AL"),
    ("gadsenal", "al", "Gadsden AL"), ("hoorveral", "al", "Hoover AL"),
    ("hooveral", "al", "Hoover AL"), ("huntsvilleal", "al", "Huntsville AL"),
    ("madisonal", "al", "Madison AL"), ("mobileal", "al", "Mobile AL"),
    ("montgomeryAL", "al", "Montgomery AL"), ("montgomeryal", "al", "Montgomery AL"),
    ("prattvilleal", "al", "Prattville AL"), ("tuscaloosaal", "al", "Tuscaloosa AL"),
    ("opelrikaal", "al", "Opelika AL"), ("opelikaal", "al", "Opelika AL"),
    ("vestazviahillsal", "al", "Vestavia Hills AL"),
    ("vestaviahillsal", "al", "Vestavia Hills AL"),
    ("annistonal", "al", "Anniston AL"), ("albertvilleal", "al", "Albertville AL"),
    ("phenixcityal", "al", "Phenix City AL"),

    # More LA
    ("alexandriala", "la", "Alexandria LA"), ("batonrougela", "la", "Baton Rouge LA"),
    ("bossiercityla", "la", "Bossier City LA"), ("kennerlaa", "la", "Kenner LA"),
    ("kennela", "la", "Kenner LA"), ("kennnerla", "la", "Kenner LA"),
    ("lafayettela", "la", "Lafayette LA"), ("lakecharlesla", "la", "Lake Charles LA"),
    ("metairiela", "la", "Metairie LA"), ("monroela", "la", "Monroe LA"),
    ("neworleansla", "la", "New Orleans LA"), ("shreveportla", "la", "Shreveport LA"),
    ("slidella", "la", "Slidell LA"),

    # More MS
    ("biloxims", "ms", "Biloxi MS"), ("brandonms", "ms", "Brandon MS"),
    ("clintonms", "ms", "Clinton MS"), ("gulfportms", "ms", "Gulfport MS"),
    ("hattieburgms", "ms", "Hattiesburg MS"), ("hattiesburgms", "ms", "Hattiesburg MS"),
    ("horn lakems", "ms", "Horn Lake MS"), ("hornlakems", "ms", "Horn Lake MS"),
    ("meridianms", "ms", "Meridian MS"), ("oliveBranchms", "ms", "Olive Branch MS"),
    ("olivebranchms", "ms", "Olive Branch MS"), ("oxfordms", "ms", "Oxford MS"),
    ("pearlms", "ms", "Pearl MS"), ("ridglandms", "ms", "Ridgeland MS"),
    ("ridgelandms", "ms", "Ridgeland MS"), ("southavenms", "ms", "Southaven MS"),
    ("starkvilles", "ms", "Starkville MS"), ("starkvillems", "ms", "Starkville MS"),
    ("tupeloms", "ms", "Tupelo MS"), ("vicksburgms", "ms", "Vicksburg MS"),

    # Additional county patterns
    ("countyofbexar", "tx", "Bexar County TX"),
    ("bexarcounty", "tx", "Bexar County TX"),
    ("countyoftravis", "tx", "Travis County TX"),
    ("traviscounty", "tx", "Travis County TX"),
    ("countyofharris", "tx", "Harris County TX"),
    ("countyofanderson", "sc", "Anderson County SC"),
    ("andersoncountysc", "sc", "Anderson County SC"),
    ("andersoncounty", "sc", "Anderson County SC"),
    ("countyofwilson", "nc", "Wilson County NC"),
    ("wilsoncounty", "nc", "Wilson County NC"),
    ("countynash", "nc", "Nash County NC"),
    ("nashcounty", "nc", "Nash County NC"),
    ("countywilson", "nc", "Wilson County NC"),
    ("countyofonondaga", "ny", "Onondaga County NY"),
    ("onondagacounty", "ny", "Onondaga County NY"),
    ("countysauk", "wi", "Sauk County WI"),
    ("countyofsauk", "wi", "Sauk County WI"),
    ("saukCounty", "wi", "Sauk County WI"),
    ("saukcounty", "wi", "Sauk County WI"),
    ("countyofdorchester", "md", "Dorchester County MD"),
    ("dorchestercountymd", "md", "Dorchester County MD"),
    ("countydorchester", "md", "Dorchester County MD"),
    ("countyinyo", "ca", "Inyo County CA"),
    ("inyocounty", "ca", "Inyo County CA"),
    ("countylake", "ca", "Lake County CA"),
    ("countynye", "nv", "Nye County NV"),
    ("nyecounty", "nv", "Nye County NV"),
    ("countynatona", "wy", "Natrona County WY"),
    ("natronacounty", "wy", "Natrona County WY"),
    ("countygalveston", "tx", "Galveston County TX"),
    ("galvestoncounty", "tx", "Galveston County TX"),
    ("countypolkia", "ia", "Polk County IA"),
    ("polkcounty", "ia", "Polk County IA"),
    ("countycolusa", "ca", "Colusa County CA"),
    ("countymunroe", "in", "Monroe County IN"),
    ("monroecounty", "in", "Monroe County IN"),
    ("countyglyn", "ga", "Glynn County GA"),
    ("glynncounty", "ga", "Glynn County GA"),
    ("countydekalb", "ga", "DeKalb County GA"),
    ("dekalbcounty", "ga", "DeKalb County GA"),
    ("countychatham", "nc", "Chatham County NC"),
    ("chathamcounty", "nc", "Chatham County NC"),
    ("countydavidson", "nc", "Davidson County NC"),
    ("davidsonncounty", "nc", "Davidson County NC"),
    ("davidsoncountync", "nc", "Davidson County NC"),
    ("countywinona", "mn", "Winona County MN"),
    ("winonacounty", "mn", "Winona County MN"),
    ("countycecil", "md", "Cecil County MD"),
    ("cecilcounty", "md", "Cecil County MD"),
    ("countyannearundel", "md", "Anne Arundel County MD"),
    ("annearundelcounty", "md", "Anne Arundel County MD"),
    ("countyportageon", "oh", "Portage County OH"),
    ("portagecounty", "oh", "Portage County OH"),
    ("countyunion", "oh", "Union County OH"),
    ("unioncountyoh", "oh", "Union County OH"),
    ("countyfairfield", "oh", "Fairfield County OH"),
    ("fairfieldcounty", "oh", "Fairfield County OH"),
    ("countygalvestontx", "tx", "Galveston County TX"),
    ("countydekalbga", "ga", "DeKalb County GA"),
    ("countyglynn", "ga", "Glynn County GA"),
    ("countychathamga", "ga", "Chatham County GA"),
    ("chathamcountyga", "ga", "Chatham County GA"),
    ("countycolusat", "ca", "Colusa County CA"),
    ("countywilsonnc", "nc", "Wilson County NC"),
    ("countywinonamn", "mn", "Winona County MN"),
    ("countybexartx", "tx", "Bexar County TX"),
    ("countyandersonsc", "sc", "Anderson County SC"),
    ("countyofsauk", "wi", "Sauk County WI"),
    ("countynashnc", "nc", "Nash County NC"),
    ("countyonondagany", "ny", "Onondaga County NY"),
]


async def probe_slug(session, slug, state, name, semaphore):
    url = f"https://api-east.viewpointcloud.com/v2/{slug}/categories"
    async with semaphore:
        try:
            async with session.get(url, timeout=aiohttp.ClientTimeout(total=10)) as resp:
                if resp.status == 200:
                    try:
                        data = await resp.json()
                        count = len(data.get("data", []))
                        return {"slug": slug, "state": state.upper(), "name": name,
                                "categories": count}
                    except Exception:
                        return {"slug": slug, "state": state.upper(), "name": name,
                                "categories": 0}
                return None
        except Exception:
            return None


async def main():
    # Build deduplicated candidate list
    seen = set(KNOWN)
    candidates = []
    for city, state, name in ROUND2:
        slug = re.sub(r'[^a-z0-9]', '', city.lower())
        if slug and slug not in seen:
            seen.add(slug)
            candidates.append((slug, state, name))

    print(f"Round 2 candidates to probe: {len(candidates)}")

    semaphore = asyncio.Semaphore(5)
    found = []
    batch_size = 25
    connector = aiohttp.TCPConnector(limit=10, ssl=False)
    headers = {"User-Agent": "Mozilla/5.0 (compatible; permit-research/1.0)"}

    async with aiohttp.ClientSession(connector=connector, headers=headers) as session:
        tasks = [probe_slug(session, slug, state, name, semaphore)
                 for slug, state, name in candidates]

        for i in range(0, len(tasks), batch_size):
            batch = tasks[i:i + batch_size]
            results = await asyncio.gather(*batch)
            for r in results:
                if r:
                    found.append(r)
            await asyncio.sleep(0.5)
            done = min(i + batch_size, len(tasks))
            if (i // batch_size) % 10 == 0 or done == len(tasks):
                print(f"  Progress: {done}/{len(tasks)} probed | {len(found)} new portals found")

    print(f"\nRound 2 found {len(found)} additional portals")

    # Merge with existing
    all_portals = list(existing)
    existing_slugs = set(p["slug"] for p in existing)
    for r in found:
        if r["slug"] not in existing_slugs:
            all_portals.append(r)
            existing_slugs.add(r["slug"])

    # Sort and save
    all_portals.sort(key=lambda x: (x.get("state", ""), x.get("name", "")))
    output_path = "/home/will/permit-api/scripts/opengov_portals.json"
    with open(output_path, "w") as f:
        json.dump(all_portals, f, indent=2)

    print(f"Total portals: {len(all_portals)}")
    print(f"Saved to: {output_path}")

    if found:
        print("\nNEWLY FOUND IN ROUND 2:")
        for p in sorted(found, key=lambda x: x["state"]):
            print(f"  {p['slug']:45s} {p['state']:5s} {p['name']} ({p['categories']} cats)")

    return all_portals


if __name__ == "__main__":
    asyncio.run(main())
